PRX/feeder.prx.org

- app/models/concerns/feeder_storage.rb
- app/models/episode.rb
- app/models/episode_builder.rb
- app/models/task.rb
- lib/prx_access.rb
- test/fixtures/crier_entry.json
- test/jobs/story_update_job_test.rb
- test/models/episode_test.rb
old crier was sending underscore, cms has always been camel.
update feeder to handle either input from hal api responses, and convert to underscore keys for use in ruby.
> Fix resource attribute case

- app/models/tasks/copy_media_task.rb
- test/models/tasks/copy_media_task_test.rb
This fixes the issues where fixer doesn't analyze the mp3 files correctly.
> Strip query params from the fixer source url

- app/representers/api/episode_representer.rb
- app/representers/api/podcast_representer.rb
fixes a bug where the representer throws an error when the prx related uris are null.
> Only show prx cms links for feeds and episodes connected to the cms

- app/controllers/api/episodes_controller.rb
- app/controllers/api/podcasts_controller.rb
- test/controllers/api/episodes_controller_test.rb
- test/controllers/api/podcasts_controller_test.rb
fixes #155 
Basically, when feeder was created, all changes came in async SQS messages SQS via `announce`.
Now that we are also affecting records via the API, need to also republish the rss xml feed when there is a change to related records via the API.
> Call publish on actions that change podcasts and episodes

- app/controllers/api/auth/episodes_controller.rb
- app/controllers/api/auth/podcasts_controller.rb
- app/controllers/api/episodes_controller.rb
- app/controllers/api/podcasts_controller.rb
- app/models/podcast.rb
- test/controllers/api/episodes_controller_test.rb
- test/controllers/api/podcasts_controller_test.rb
> Redirect authorized access to unpublished instead of returning 404

- app/jobs/story_update_job.rb
fixes #181 
now that episodes also have a notion of being published or not, mirror this story value in the episode instead of deleting episodes for unpublished stories.
> Treat unpublish announcement as an update not a delete

- app/models/episode.rb
- test/models/episode_entry_handler_test.rb
- test/models/episode_test.rb
#178 
feeder was not correctly checking to see if an episode had audio in a processing state, and was showing episodes with no complete audio just as it would an episode which has no audio at all (it is ok in feeder to show an episode which lacks any audio, it just isn't ok to show one with audio that is still processing).
> Prevent item from showing up in feed while audio still processing

- app/models/episode.rb
- app/representers/api/episode_representer.rb
- db/migrate/20170123205547_add_adzerk_keyword.rb
- db/migrate/20170123205547_add_external_keyword.rb
- db/schema.rb
- test/models/episode_test.rb
#102
Adds a unique + unchanging identifying keyword to each published episode (combo of title, published_at, and guid at time of first publishing). 
Adzerk keywords are case-insensitive, can contain spaces, but can't contain commas or colons; and are capped at 512 characters for all keywords for a given request. I've limited this adzerk keyword (which we'll use for identifying + [reporting](http://dev.adzerk.com/docs/keyword-targeting#section-reporting-on-keywords) purposes) to 30 characters, to leave plenty of space for us to potentially use other keywords for [targeting](http://dev.adzerk.com/docs/keyword-targeting) purposes down the line.
> Add external keyword to episodes for tracking purposes

- app/controllers/api/episodes_controller.rb
- app/controllers/api/podcasts_controller.rb
- app/models/media_resource.rb
- test/controllers/api/episodes_controller_test.rb
- test/controllers/api/podcasts_controller_test.rb
- test/factories/media_resource_factory.rb
- test/models/episode_test.rb
- test/models/media_resource_test.rb
Found some issues while working on using the API directly to publish episodes
> Import script fixes

- app/jobs/story_update_job.rb
- test/jobs/story_update_job_test.rb
Should fix the TypeError we're seeing on New Relic. 
```
TypeError: no implicit conversion of Symbol into Integer
/app/app/jobs/story_update_job.rb:  21:in `[]'
/app/app/jobs/story_update_job.rb:  21:in `receive_story_update'
```
> Parse data JSON before checking its validity status

- db/migrate/20170223114125_create_episode_images.rb
In RDS, it must be added by a superuser before this migration is run.
#202
> Do not add the uuid extension

- app/jobs/story_update_job.rb
We were trying to access check `body[:status]` instead of `body['status']`, and so all async episode updates were rejected. Instead, since we're turning the data into a Story anyway, just check the story's `status`.
> Fix error in JSON parsing

- app/models/episode_story_handler.rb
Small fix, just don't override the episode url when it is already set.
> only override with story alt link when episode link is null

- app/models/episode_story_handler.rb
- app/models/podcast_series_handler.rb
- app/models/tasks/copy_media_task.rb
- test/fixtures/prx_story_all.json
- test/models/episode_story_handler_test.rb
- test/models/tasks/copy_media_task_test.rb
> Use storage audio urls

- app/helpers/podcasts_helper.rb
- app/models/concerns/text_sanitizer.rb
- app/models/episode.rb
- app/models/episode_story_handler.rb
- app/models/podcast.rb
- app/representers/api/base_representer.rb
- app/representers/api/episode_representer.rb
- app/representers/api/podcast_representer.rb
- app/views/podcasts/show.rss.builder
- config/initializers/white_list.rb
- db/migrate/20170309181410_podcast_str_to_text.rb
- db/schema.rb
- test/factories/episode_factory.rb
- test/integration/podcast_request_test.rb
- test/models/concerns/text_sanitizer_test.rb
- test/representers/api/episode_representer_test.rb
> Sanitize text

- app/models/episode_entry_handler.rb
- app/models/episode_story_handler.rb
- app/views/podcasts/show.rss.builder
- test/models/episode_entry_handler_test.rb
When a feed uses libsyn, like twww, then the episode links are to the mp3 at libsyn.com
In cms, when these are imported, they get blanked out.
> Fix episode link from libsyn to go to the enclosure

- app/controllers/api/episodes_controller.rb
- app/controllers/api/podcasts_controller.rb
- test/controllers/api/podcasts_controller_test.rb
fixes #239 
the `included()` method is only used when calling find on a single resource, so by moving the `with_deleted` scope to that, we avoid having it affect the listing/index actions, and so deleted records don't come back.
> include deleted records only with find requests

- app/representers/api/episode_representer.rb
- app/representers/api/image_representer.rb
- app/representers/api/media_resource_representer.rb
- db/migrate/20170921182535_remove_episodes_image_url.rb
- db/schema.rb
- test/factories/episode_image_factory.rb
- test/models/episode_image_test.rb
- test/representers/api/episode_representer_test.rb
Fixing some things to make the feeder import -> cms work better
> Add original urls, episode images

- app/models/episode.rb
- app/models/episode_entry_handler.rb
- app/models/episode_story_handler.rb
- app/models/podcast.rb
- app/representers/api/episode_representer.rb
- app/representers/api/podcast_representer.rb
- app/views/podcasts/show.rss.builder
- db/migrate/20170926204117_add_podcast_tags.rb
- db/migrate/20170926210603_add_episode_tags.rb
- db/migrate/20170928174959_add_clean_title_to_episodes.rb
- db/schema.rb
- lib/prx_access.rb
- test/factories/episode_factory.rb
- test/fixtures/prx_story_all.json
- test/fixtures/prx_story_invalid_identifiers.json
- test/fixtures/prx_story_zero_identifiers.json
- test/integration/podcast_request_test.rb
- test/models/episode_story_handler_test.rb
- test/models/episode_test.rb
- test/models/podcast_series_handler_test.rb
- test/models/podcast_test.rb
- test/models/tasks/copy_media_task_test.rb
- test/representers/api/episode_representer_test.rb
- test/representers/api/podcast_representer_test.rb
#255 
along with this, we'll change CMS to keep track of a story's season as well (https://github.com/PRX/cms.prx.org/issues/319), possibly send the season + episode info to feeder when it creates an EpisodeDistribution for a story (tbd, question in #319), and also update Publish to allow users to set all these fields. (https://github.com/PRX/publish.prx.org/issues/428). This is a blocker for #428.
> Support new Apple Podcasts tags for iOS11

- app/models/tasks/copy_image_task.rb
- app/models/tasks/publish_feed_task.rb
Lots of `NoMethodError: undefined method `published_url' for nil:NilClass` in CloudWatch for feeder-staging after last attempted podcast import (of very large feed). Not sure where it could be coming from, so let's add lots of logging around everywhere temporarily and then rerun the same import in staging again.
> log anywhere that published_url is called on something that could be nil

- app/controllers/api/auth/podcasts_controller.rb
- app/controllers/api/authorizations_controller.rb
- app/controllers/api/base_controller.rb
- app/models/authorization.rb
- app/representers/api/authorization_representer.rb
- test/controllers/api/auth/podcasts_controller_test.rb
- test/models/authorization_test.rb
- test/representers/api/authorization_representer_test.rb
- test/test_helper.rb
See #262.
Assumes a known structure to the `podcasts.prx_account_uri`.  But I think that's okay for now.
> Filter authorized podcasts

- app/representers/api/episode_representer.rb
- buildspec.yml
- config/initializers/shoryuken.rb
- config/shoryuken.yml
> Fix worker env vars

- app/controllers/api/episodes_controller.rb
- test/controllers/api/episodes_controller_test.rb
When a cms story episode distribution request inserts an episode, but the response it not correctly returned or processed, a retry of the distribution will fail with a dupe key on the prx id (story id).
With this change, the episode controller will lookup an existing story, and update it.
> Check for existing episode for a story id before inserting

- app/jobs/application_job.rb
Had some issues after #281 merged -- 
`StoryUpdateJob/executeArgumentError | wrong number of arguments (given 0, expected 1)`
think this should solve?
> Use correct syntax for around_perform

- Gemfile
- Gemfile.lock
- app/controllers/api/episodes_controller.rb
- app/controllers/api/podcasts_controller.rb
- app/representers/api/paged_collection_representer.rb
- config/initializers/hal_api.rb
- config/initializers/say_when.rb
- docker-compose-ci.yml
- docker-compose.yml
- test/controllers/api/episodes_controller_test.rb
- test/controllers/api/podcasts_controller_test.rb
Upgrade hal api gem, to get NewRelic error handling fixes.  Plus other minor-version fixes in the v0.3.x upgrade ... which were a bit more applicable to PRX/cms.prx.org#360 than here.
> Upgrade hal_api-rails

- app/models/episode.rb
- app/representers/api/episode_representer.rb
- test/representers/api/episode_representer_test.rb
Make it easier for publish to check if an episode is "complete".  Include a `is_feed_ready` boolean attribute, using Feeder's own logic of when an episode is ready to go in the feed.
> Episode feed-ready indicator

- Gemfile
- Gemfile.lock
- app/models/episode.rb
- test/controllers/api/episodes_controller_test.rb
If you PUT an episode with _the same_ media hrefs, the update will be ignored.  But it did attempt to update the other `Content` fields - which would result in a bunch of fields being nulled out.  And no `CopyMediaTask` is created to get them re-updated, since the underlying file didn't change.
The result would be nulled-out `:mime_type / :file_size / :duration` on the Content, which made Dovetail angry.
This PR ignores null-updates to the `type / size / duration` fields.  Even if you explicitly PUT a `media: [{href: "href1", type: null}]`, it will refuse to null them out.
I was very explicit in targeting those 3 fields, as they're in the `MediaResourceRepresenter`.  So even though the `Episode.update_contents` allows all sorts of other fields through, the representer will not.
> Fix episode update endpoint

- app/models/episode.rb
- test/controllers/api/auth/episodes_controller_test.rb
- test/controllers/api/episodes_controller_test.rb
- test/factories/media_resource_factory.rb
- test/models/episode_test.rb
For #311.
When setting `{ media: [] }` through an API create/update, always append new Contents instead of looking for existing.  This ensures that any media change coming through the API always reprocesses the files.
This _will_ result in some churn in the resulting mp3 urls, and thus the dovetail arrangement digests/urls.  So definitely don't want anyone automating a bunch of non-change PUTs to the episode media.  But I don't _think_ anyone is doing that right now anyways.  Should only PUT `media:[]` if it's actually changed.
> API media updates

- app/models/concerns/porter_encoder.rb
- test/models/concerns/porter_encoder_test.rb
When we get an HTTP source file (like from CMS) with url-encoded characters in it, we need to decode those before calling the S3 API via Porter.
> Url-decode S3 paths for HTTP sourced files

- Gemfile
- Gemfile.lock
- app/models/episode.rb
- app/representers/api/episode_representer.rb
- test/models/episode_test.rb
- test/representers/api/episode_representer_test.rb
Needed for https://github.com/PRX/dovetail.prx.org/issues/344
This PR adds an `explicit_content` read-only attribute to episode which is
`true` if the podcast is explicit and the episode doesn't specify, or the episode is explicit
`false` if the podcast is clean and the episode doesn't specify, or the episode is clean
otherwise `nil`
This can then be used in DT to target clean only, or avoid explicit episodes
> Add `explicit_content` attribute

- app/controllers/api/episodes_controller.rb
I recently added a bunch of `included` to speed up index queries.  But apparently it's slightly slowing down show queries ... which is 99% of the traffic coming from Dovetail.
Revert that, only for show.
> Prevent N+1 via includes only on index

- app/controllers/api/auth/episodes_controller.rb
- app/controllers/api/auth/podcasts_controller.rb
- app/representers/api/api_representer.rb
- app/representers/api/auth/episode_representer.rb
- app/representers/api/auth/podcast_representer.rb
- config/routes.rb
- test/representers/api/api_representer_test.rb
- test/representers/api/auth/episode_representer_test.rb
- test/representers/api/auth/podcast_representer_test.rb
> Fill in and fix some authorized links

- app/models/authorization.rb
- app/models/episode.rb
- app/policies/episode_policy.rb
- app/policies/podcast_policy.rb
- config/initializers/prx_auth.rb
- test/controllers/api/auth/episodes_controller_test.rb
- test/controllers/api/auth/podcasts_controller_test.rb
- test/controllers/api/authorizations_controller_test.rb
- test/controllers/api/episodes_controller_test.rb
- test/controllers/api/podcasts_controller_test.rb
- test/models/authorization_test.rb
- test/policies/episode_policy_test.rb
- test/policies/podcast_policy_test.rb
- test/representers/api/authorization_representer_test.rb
This is the first PR that is ready for review to start using the new scope-based tokens for checking permissions.
There are a couple of potential issues I want to flag: first, I have left things requiring the `admin` meta-scope to allow deleting episodes. That's because the existing behavior only allowed admins to delete episodes, but we didn't have a real scope that seemed to fit that case. I think this is at best a stopgap and we should plan to retire that scope and determine what we want to do going forward (personally, I think you can do as much damage editing an episode as deleting it but maybe I don't know everything going on here...)
Second, this is the introduction of draft semantics and they may not work as you initially assume, so probably good to really make sure you're …
> Scope-based policies

- config/initializers/config_env.rb
- env-example
Closes #365
This value is not defined in aws-secrets for production, so the default change will apply.
> Update default feed webMaster value

- app/jobs/application_job.rb
We were sending job exceptions to New Relic, but not re-raising them.
Also did a bit of reading on [ActiveJob Retries](https://github.com/ruby-shoryuken/shoryuken/issues/553).  I _think_ what happens now is:
- A job raises an exception
- This handler catches it, logs to new relic, and re-raises
- The SQS message is _not_ deleted, but ends up hidden for 1 hour (our visibility timeout)
- After 10 receives/retries (10 hours?), the SQS message goes into the DLQ
> Re-raise job errors

- app/controllers/api/auth/episodes_controller.rb
- app/controllers/api/auth/podcasts_controller.rb
- app/models/authorization.rb
- app/representers/api/auth/episode_representer.rb
- app/representers/api/auth/podcast_representer.rb
- test/controllers/api/auth/episodes_controller_test.rb
- test/controllers/api/auth/podcasts_controller_test.rb
Castle uses a wildcard token to scrape Feeder data from the API, using the `?since=2021-06-25` query param to find updated_at >= some time.
We need castle to also be able to get deleted podcasts/episodes from that same API.
> Include deleted for wildcard token

- app/controllers/api/auth/episodes_controller.rb
- app/controllers/api/episodes_controller.rb
Hit a bug with a script scraping the Feeder API -
Expected the most recent feed-rss episode to be first at `/api/v1/episodes`.  But because the episode was actually created 3 years ago and we're sorting by `id: :desc` ... it was way down the list.
This sorts both the authorized and public episode endpoints by published_at (and released_at) DESC.  I don't think this will cause any issues, with an API user depending on that `id desc` order.  The main feed-scraper is Castle, and since it uses `?since` it's already getting an explicit `order('updated_at asc')`.
> Sort episodes by published_at

- app/models/episode.rb
- app/models/podcast.rb
- test/models/episode_test.rb
Cleanup inconsistencies in the `podcasts.enclosure_template` field, ahead of multi-feed work.
- Fix default enclosure templates - the `/_/` in the path is no longer necessary since DTR gets all the ALB traffic.
- We don't set `podcasts.path` anymore - but make sure we always use the podcast_id instead of the path in enclosure urls.  
- DTR only understands podcast_ids, not aliases, so I've already hardcoded the id into a bunch of enclosure templates that were aliased.
After this deploys, will need to do some manual database cleanup to get as many shows as possible back to the default: 
```
https://dovetail.prxu.org/{slug}/{guid}/{original_filename}
```
This includes:
I don't love the spotify redownloads and listener_episode churn when enclosures change.  But it might be worth doing that …
> Cleanup DT3 enclosure templates

- app/models/episode.rb
- test/models/episode_test.rb
If the episode has video enclosures, use that type, not the feed.
> Handle video enclosures in feeds differently

- app/models/feed.rb
- app/models/podcast.rb
- app/representers/api/auth/feed_representer.rb
- env-example
- test/controllers/api/auth/feeds_controller_test.rb
- test/models/feed_test.rb
- test/representers/api/auth/feed_representer_test.rb
- test/test_helper.rb
Couple more Podcast-Feed APIs needed to build out the Publish pages.
- Include a link on the feed, for the _private_ feed proxy `p.prxu.org`.  Will need to add those ENVs to Feeder.
- Simple attribute getter/setter for feed tokens.  (Will be easier than attempting a nested resource for them).
> More feeds APIs

- app/helpers/podcasts_helper.rb
- app/models/feed.rb
- app/models/podcast.rb
- app/representers/api/auth/feed_representer.rb
- app/representers/api/podcast_representer.rb
- app/views/podcasts/show.rss.builder
- db/migrate/20220817212106_move_description_to_feed.rb
- db/schema.rb
- test/factories/feed_factory.rb
- test/factories/podcast_factory.rb
- test/representers/api/auth/feed_representer_test.rb
Backend work for #436.
Moves 3 fields from `Podcast` to `Feed`.  But keeps them proxied to the `podcast.default_feed` so existing APIs continue working.
> Move subtitle/description/summary to feed

- app/controllers/api/episodes_controller.rb
- app/models/episode.rb
- app/representers/api/api_representer.rb
- app/representers/api/auth/podcast_representer.rb
- app/representers/api/authorization_representer.rb
- app/representers/api/podcast_representer.rb
- config/routes.rb
- test/controllers/api/episodes_controller_test.rb
- test/models/episode_test.rb
Closes #487.
```
GET /api/v1/podcasts/:podcast_id/guids/:id
GET /api/v1/authorization/podcasts/:podcast_id/guids/:id
```
> Find by item guid

- app/controllers/fake_controller.rb
- app/helpers/application_helper.rb
- app/javascript/application.js
- app/javascript/controllers/toast_controller.js
- app/views/layouts/_alerts.html.erb
- app/views/layouts/application.html.erb
Use toasts to display flash messages.  Setup a demo for `flash.now[:notice]`.
> Init toasts for flash messages

- Gemfile
- Gemfile.lock
- app/controllers/api/base_controller.rb
- app/controllers/application_controller.rb
- app/controllers/fake_controller.rb
- app/views/errors/forbidden.html.erb
- app/views/fake/show.html.erb
- config/locales/en.yml
Feeder already has the pundit gem for its API endpoints.
This adds it for the top-level controller, and adds some custom handling.  Users will normally never see these pages unless they're doing something nefarious.  But good to handle them.
> Init pundit error handling

- app/assets/stylesheets/shared/form.scss
- app/helpers/feeder_form_builder.rb
- app/javascript/controllers/slim_select_controller.js
- app/views/fake/show.html.erb
Wooo! Slim Select V2 is not backwards compatible from a styling perspective. But I think I got all the differences.
This will be a big diff as slim-select got rid of some wrapper classes, so many things have been moved around the file.
When we port this over to the other sites, we will need to upgrade slim select, otherwise many selects will have weird styling.
> updated styles for slim select v2

- app/assets/stylesheets/card.scss
- app/assets/stylesheets/shared/header.scss
- app/views/fake/index.html.erb
- app/views/layouts/_nav.html.erb
- app/views/layouts/_subnav.html.erb
Realized, I forgot about these when creating the Card PR last week. 
- This sets up the patterns for the two column episode list. `.episode-card` (Check it own on the fake/index path)
- It also touches nav files a little by moving away from bootstrap classes to styles defined in stylesheets as we resolved to do that in the cards PR. Should be cleaner.
> Create styles for episode list cards

- app/controllers/api/base_controller.rb
- app/controllers/api/feeds_controller.rb
- app/controllers/application_controller.rb
For api requests, this PR prevents setting a session.
To verify:
- `/fake`: does set a cookie and insert a row in the sessions table
- `/api/v1`: (api base controller) does not set a cookie or insert a row into the sessions table
- `/api/v1/feeds`: feeds controller (application controller), does not set a cookie or insert a row into the sessions table
> Skip setting session for api

- README.md
- config/newrelic.yml
- config/puma.rb
- docker-compose-ci.yml
- docker-compose.yml
- env-example
- Doesn't talk about docker - assume local dev
- No mention of CMS, Publish or Crier - those are on the way out
> Cleanup readme

- app/views/layouts/application.html.erb
My recommendation would be to standardize on the PRX icon for the time being. If we want to develop a meaningful set of icons for each app (Feeder, Augury, etc), or functions (publishing, metrics, etc) down the road, that could be beneficial. But until then, I think just using the vanilla icon gets us in a good spot.
> Use standard PRX favicon

- app/models/apple/episode.rb
- app/models/enclosure_url_builder.rb
- test/models/apple/episode_test.rb
- test/models/apple/podcast_container_test.rb
- test/models/enclosure_url_builder_test.rb
This PR Fixes a couple problems with the urls that the Apple Subscriptions code uses:
1) It removes the `prefix` from the enclosures that the apple api uses.  This decouples the GET from the Dovetail CDN from the typical redirect flow that end users experience. The 'reduced' enclosure url should directly reference the DTR redirect endpoint.
2) It fixes up the feed enclosure to make sure that we're building _authed_ enclosures for the episodes -- the same as what are referenced in the private feed.  This ensures that we are getting the stitched audio from the private feed.  Previously this was getting the enclosure for the default (public) feed.
> Extract a base enclosure url

- app/models/apple/publisher.rb
- test/models/apple/publisher_test.rb
Already fixed in #580, but this adds some test coverage.
> Fixup the publisher's api reference is passed in

- app/javascript/controllers/audio_breakpoint_controller.js
- app/javascript/controllers/audio_breakpoints_controller.js
- app/javascript/controllers/waveform_inspector_controller.js
- app/javascript/util/convertSecondsToDuration.js
- config/importmap.rb
This should run locally, but the real test is if the imports continue to 404 on staging.
> Fix js import used by audio segmenter page controllers

- Gemfile.lock
- bin/rails
- bin/rake
- bin/spring
- config/application.rb
- config/environments/test.rb
This PR will:
- update spring
- setup binstubs to use spring
Most noticeable when you are running a single test repeatedly, for instance. This will speed up rails boot time.
```bash
bash-5.1.16$ time : $(echo "1" | ./bin/rails c)                                                                
real    0m5.128s                                                                                                       
user    0m2.220s    
sys     0m1.302s 
```
versus
```bash
bash-5.1.16$ time : $(echo "1" | ./bin/rails c)                                       
DEBUGGER[spring app    | feeder.prx.org | started 10 secs ago | development mode#61061]: Attaching after process 60898 fork to child process 61061
Running via Spring preloader in process 61061 …
```
> Setup spring binstubs

- app/assets/stylesheets/shared/card.scss
- app/assets/stylesheets/shared/form.scss
- app/views/episodes/_form_audio.html.erb
- app/views/episodes/_form_image.html.erb
- app/views/episodes/_form_main.html.erb
- app/views/episodes/_form_tags.html.erb
- app/views/podcasts/_form_main.html.erb
- Restyles help text (creates a few custom classes)
- Renamed help-text button
- Reinstates changed state styling (`.is-changed`)
- Moves the help-text button outside of `form-floating` class (this is the bulk of the code change you'll see)
- Creates the `prx-field-group` class that uses CSS grid to allow `invalid-feedback` text appears on its own row without affecting the rest of the styling
h/t @rpeterman-gp
> Fix form state styling

- app/controllers/podcasts_controller.rb
- app/views/podcasts/index.html.erb
> Sort Dropdown Fixes

- app/assets/stylesheets/shared/table.scss
- app/helpers/application_helper.rb
- app/views/episodes/audio/_complete.html.erb
- app/views/episodes/audio/_modal.html.erb
- app/views/images/_complete.html.erb
- app/views/images/_modal.html.erb
After #619.  Part of #618.
Display metadata for audio/video/image files.
> File metadata modals

- app/assets/stylesheets/app/calendar.scss
- app/assets/stylesheets/shared/layout.scss
- app/controllers/podcast_planner_controller.rb
- app/helpers/podcast_planner_helper.rb
- app/javascript/controllers/count_controller.js
- app/views/podcast_planner/_calendar.html.erb
- app/views/podcast_planner/_form_date_calculator.html.erb
- app/views/podcast_planner/_form_main.html.erb
- app/views/podcast_planner/_form_side.html.erb
- app/views/podcast_planner/show.html.erb
- config/locales/en.yml
closes: #606 
Now that we have a working calendar (!!!EXCITING!!!) I thought we could take a pass at the verbiage and the layout of the calendar. This PR's changes will get us closer to what exists in Publish currently where we've received a lot of neutral to positive feedback. (NOTE: I think we can open a new ticket to explore enhancements to this feature that go beyond the existing functionality in this PR.)
There were a lot of places where we had help text, headers, and field labels that felt a little redundant or overly technical in its use, so I attempted to clean It up.
Also, I reverted this to a single column layout like we have now. I think this will serve our producers finely enough until we get the time to really rethink the feature in the future.
> Podcast Planner verbiage and layout

- app/models/concerns/image_file.rb
- app/models/media_resource.rb
- app/models/tasks/copy_image_task.rb
- app/models/tasks/copy_media_task.rb
- test/models/concerns/image_file_test.rb
- test/models/tasks/copy_image_task_test.rb
- test/models/tasks/copy_media_task_test.rb
Found a bunch of old files in prod, with `status: "complete"` but missing a bunch of metadata fields.  I'm guessing they just predate when we added the metadata to the DB, or something was missing in the Fixer callbacks?
Anyways, I need to fix them, but their original urls are long gone.
Generally, when re-copying media (for files that already succeeded) - we can and should use the `f.prxu.org` url as the source.  Instead of the `original_url`, which in many cases is long gone/broken.
> Re-copying complete media

- app/jobs/publish_apple_job.rb
- app/jobs/publish_feed_job.rb
- app/models/apple/config.rb
- app/models/episode.rb
- config/shoryuken.yml
- lib/tasks/sqs.rake
- test/factories/apple_config_factory.rb
- test/jobs/publish_apple_job_test.rb
- test/jobs/publish_feed_job_test.rb
Sets up a new Apple sync/publish job as part of a testing strategy. This will kick off apple publishing with rss publishing. Once this has settled down, then we can merge this back into the PublishFeedJob to get the blocking semantics (Apple publishing is blocking RSS publishing).
> Apple sync job

- app/models/apple/episode.rb
- test/factories/apple_episode_api_response.rb
- test/factories/apple_episode_factory.rb
- test/factories/apple_podcast_delivery_factory.rb
- test/factories/apple_podcast_delivery_file_factory.rb
- test/factories/apple_show_factory.rb
- test/models/apple/episode_test.rb
- test/models/apple/podcast_container_test.rb
Fixes a condition where the episode audio can be fully synced with apple and yet the episode in an unpublished state.  This PR makes insures that we include such an episode for the publishing process as well.  It will re-sync with the api, polling everything as usual (except the podcast container), and marked as published in Apple remote state.
> Consider drafting episodes as not-synced

- app/models/apple/upload_operation.rb
- docker-compose.yml
Fixes the thread pool logging.
Currently, the publishing code tags the logs for easy searching. But since we're spawning threads, those are missing the thread-local tags. This PR makes sure that the thread local logging config has the right tags.
> Fix thread pool logging

- app/models/apple/show.rb
This reverts commit 3d006006285c5f31e07dae0d65e5fbbea9723d6f.
Removes a incorrectly added splat operator.
> Revert "Last argument as keyword parameters is deprecated"

- app/models/media_resource.rb
- test/models/media_resource_test.rb
Okay, so... I had written a [mark_for_replacement](https://github.com/PRX/feeder.prx.org/blob/main/app/models/media_resource.rb#L170) method to mimic how `mark_for_destruction` works.  But it would set both `deleted_at` and `replaced_at`.
This gets called from the [media=](https://github.com/PRX/feeder.prx.org/blob/main/app/models/concerns/episode_media.rb#L41) setter, which is called for API and Announced CMS updates.
But - apparently when you `.mark_for_destruction` something and then save its parent... it _ignores_ any other pending changes to that record.  So it was just setting `deleted_at` and ignoring the changed `replaced_at` field.
~Took a look at hacking/extending the `paranoia` gem to make it also set this field.  But that was complicated.  This takes an additional SQL …
> Fix replaced media coming from CMS

- app/models/apple/episode.rb
- app/models/episode.rb
- app/views/podcasts/show.rss.builder
- test/models/episode_test.rb
Partially solves https://github.com/PRX/feeder.prx.org/issues/589 by setting up a default.
Sets up a helper method which wraps the subtitle and title as fallback defaults. This is so that the description is not left blank in the RSS feed.  The motivation here is that Apple validates the presence of the description via interactions to their API. So if the feed is consumed by the RSS poller with a blank description, then unrelated API operations can fail with validation errors.
> Set default description for publishing

- app/models/apple/podcast_container.rb
- app/models/apple/publisher.rb
- test/models/apple/podcast_container_test.rb
Fixes a bug where an old (finished) upload was polling for metadata on an expired CDN url.   This sets up a guard, and will only reset and refresh "source" file metadata if needed.
> Fix case where the source metadata is not reset

- app/models/apple/episode.rb
- app/models/apple/show.rb
Sets up logging for _all_ episodes stuck in the audio asset state polling loop.
> Log pending audio asset state transitions

- app/models/apple/episode.rb
- app/models/episode.rb
- test/models/apple/episode_test.rb
Fixes a bug where the enclosure filename was not being properly parameterized by the feed.  Handles the case where the file extensions of the main feed don't match the private feed in Apple publishing.
> Pass in the private feed to get the enclosure filename

- app/assets/stylesheets/shared/form.scss
- app/views/episodes/_form_main.html.erb
- app/views/episodes/_form_tags.html.erb
- app/views/fake/index.html.erb
- app/views/feeds/_form_ad_zones.html.erb
- app/views/feeds/_form_audio_format.html.erb
- app/views/feeds/_form_auth.html.erb
- app/views/feeds/_form_overrides.html.erb
- app/views/feeds/_form_status.html.erb
- app/views/images/_complete.html.erb
- app/views/images/_new.html.erb
- app/views/images/_processing.html.erb
- app/views/podcast_engagement/show.html.erb
- app/views/podcast_planner/_form_date_calculator.html.erb
- app/views/podcast_planner/_form_side.html.erb
- app/views/podcasts/_form_main.html.erb
- app/views/podcasts/_form_status.html.erb
- app/views/podcasts/show.html.erb
- Uses card headers with no border and a shadow for base cards
- `card-shadow-light` to replace the black (I though the black was too stark), light blue still available for other card headers too.
- Adds cards to the episode planner
- fixes a bug where the `invalid-feedback` message was added before the help text.
In review:
> Consistent card groupings

- app/assets/stylesheets/shared/bootstrap-variables.scss
- app/controllers/podcasts_controller.rb
- app/javascript/controllers/podcast_metrics_controller.js
- app/views/episodes/_form_main.html.erb
- app/views/feeds/_tabs.html.erb
- app/views/podcasts/_podcast.html.erb
- app/views/podcasts/show.html.erb
- config/importmap.rb
- config/initializers/prx_auth.rb
- config/locales/en.yml
- env-example
Adds highcharts to display Castle data on `podcasts#show`.
To make this work locally, you need to:
- Add the new `CASTLE_HOST=castle.staging.prx.tech` to your `.env`
- Have [puma-dev installed/running](https://github.com/PRX/internal/wiki/Guide%3A-Local-Development-Environment#install-puma-dev)
- `echo 3002 > ~/.puma-dev/feeder.prx`
- Change your `PRX_CLIENT_ID` and `PRX_CLIENT_SECRET` to a client app for `.test` (`x55P20kzJzy4xnZjm4J5wxRnhJWtG0tpgUwo71EA` is setup for `https://feeder.prx.test` in ID staging)
- Open your browser to `https://feeder.prx.test/podcasts`
> Podcast metrics

- app/controllers/application_controller.rb
- app/controllers/episodes_controller.rb
- app/helpers/application_helper.rb
- app/helpers/embed_player_helper.rb
- app/javascript/controllers/clipboard_controller.js
- app/models/episode.rb
- app/models/feed.rb
- app/models/podcast.rb
- app/views/episodes/_form_distribution.html.erb
- app/views/episodes/_form_status.html.erb
- app/views/podcasts/show.rss.builder
- config/locales/en.yml
- env-example
- lib/prx_access.rb
Fixes #633.  Fills in the Episode distribution card.
State of this form varies a bit based on episode state (new, is media uploaded, etc).
This _does not_ do the magic for "previewing" an embed-player before the episode publishes.  But I think that's the right call for this component.
> Episode distributions card

- app/models/apple/podcast_container.rb
- app/models/episode.rb
- test/models/episode_test.rb
Fixes a bug where the call to `delete_all` via a `has_many through: ..` throws an ORM exception.
This unifies the code paths in the episode publish method with the metadata reset in the Apple::PodcastContainer class method.
Touches on https://github.com/PRX/feeder.prx.org/issues/685 where the assumption is that if we have _missing_ local copies of the podcast delivery apple data, we intend to re-upload.  The presence of the local podcast deliveries metadata indicates that _we_ have records of doing the uploads, even if [Apple discards them](https://github.com/PRX/feeder.prx.org/issues/680)
> Fix destroy through relations

- app/assets/stylesheets/shared/form.scss
- app/helpers/feeder_form_builder.rb
- app/javascript/controllers/click_controller.js
- app/javascript/controllers/confirm_field_controller.js
- app/javascript/controllers/slim_select_controller.js
- app/models/episode.rb
- app/views/episodes/_form_distribution.html.erb
- app/views/episodes/_missing_drafts.html.erb
- app/views/episodes/new.html.erb
- app/views/feeds/_form_main.html.erb
- app/views/layouts/_confirm_field.html.erb
- app/views/layouts/application.html.erb
- app/views/podcasts/_form_main.html.erb
- config/locales/en.yml
Confirms when a bunch of fields are changed, as Publish does.
- Podcast Settings -> Owner
- Podcast Settings -> Complete (only when changing to "complete")
- Feed -> File Name
- Feed -> Slug (non default feeds)
- Feed -> Public Feed URL (different text depending if you're creating/deleting/changing)
- Feed -> New Feed URL (different text depending if you're creating/deleting/changing)
- Episode -> GUID
- Episode -> New (when you have 0 future-drafts planned)
> Field change confirmations

- app/assets/stylesheets/shared/bootstrap-variables.scss
- app/assets/stylesheets/shared/form.scss
Woof. That was thorny, but once I realized that the .`ss-main` selector only applied to the selectbox and not the dropdown, I could make progress. 
A few notes in the code.
To replicate:
- Podcasts > Settings and remove the Itunes category and save, this should prompt validation. Ensure that the icons are present and not visible in the dropdown.
> Fixes Itunes Category & sub Category styling

- app/controllers/feeds_controller.rb
- app/controllers/podcast_engagement_controller.rb
- app/controllers/podcasts_controller.rb
- app/models/episode.rb
- app/models/feed.rb
- app/models/validators/http_url_validator.rb
- app/views/episodes/_form_distribution.html.erb
- app/views/episodes/_form_main.html.erb
- app/views/feeds/_form_main.html.erb
- config/locales/en.yml
- test/controllers/feeds_controller_test.rb
Adds a bunch of validations that existed in Publish/CMS.  I fixed all prod data that didn't adhere to these, so shouldn't cause any issues with CMS -> Feeder data syncing.
See [the parity check spreadsheet](https://docs.google.com/spreadsheets/d/1ZidmwH3JUM4ag2eb1i5YWkbMqx2PsUrSAQ8Te6LdoPM/edit#gid=0) for a list of things I've added here.
> Backfill validations

- app/javascript/controllers/confirm_field_controller.js
- app/views/episodes/_form_distribution.html.erb
- app/views/feeds/_form_main.html.erb
- app/views/layouts/_confirm_field.html.erb
- app/views/layouts/_subnav.html.erb
- app/views/podcasts/_form_main.html.erb
Refactors the field-changed stimulus controller a bit.  So we can intercept "enter" keydown events, and prompt the user to confirm the change before the form submits.
(Previously, the form would submit, and _then_ you'd get prompted.  But the change was already saved, so not ideal)
> Confirm when enter pressed

- app/assets/stylesheets/shared/episode-card.scss
- app/assets/stylesheets/shared/form.scss
- app/assets/stylesheets/shared/layout.scss
- app/views/episodes/index.html.erb
- app/views/episodes/media/_complete.html.erb
- app/views/episodes/media/_error.html.erb
- app/views/episodes/media/_new.html.erb
- app/views/episodes/media/_processing.html.erb
- app/views/fake/audio_segmenter.html.erb
- app/views/fake/index.html.erb
- app/views/images/_error.html.erb
- app/views/images/_new.html.erb
- app/views/images/_processing.html.erb
- app/views/layouts/_nav.html.erb
- app/views/layouts/_subnav.html.erb
- app/views/layouts/application.html.erb
- app/views/podcast_switcher/_dropdown.html.erb
- app/views/podcasts/_podcast_page.html.erb
- app/views/podcasts/index.html.erb
- app/views/podcasts/show.html.erb
will comment inline.
Review:
In podcasts controller, change this to:
`@podcasts = add_sorting(filtered_podcasts).where(id: 815)`
To Do:
> HOTFIX: style clean up for only one podcast

- app/javascript/controllers/podcast_metrics_controller.js
- app/views/podcasts/show.html.erb
- config/locales/en.yml
For new podcasts (or in local dev, all new podcasts you create) ... Castle will for some time have no data.
Handle this, and display a nicer message:
> Handle castle not found error

- app/jobs/publish_feed_job.rb
- app/models/podcast.rb
- app/models/publishing_pipeline_state.rb
- app/models/publishing_queue_item.rb
- test/models/publishing_pipeline_state_test.rb
This PR extracts the RSS publishing out of the pipeline semantics for the moment, until something like #714 can land. The RSS pipeline state transitions stub the actual RSS generation (which happens first thing in the job) so we can still observe and test the podcast partitioned concurrency primitives.
This also adds some additional logging around the publishing pipeline and queue.
> Temporarily extract RSS generation from pipeline

- app/controllers/episodes_controller.rb
- app/controllers/feeds_controller.rb
- app/controllers/podcast_engagement_controller.rb
- app/controllers/podcasts_controller.rb
Oversight: forgot to call `podcast.publish!` to write the updated RSS feed.
This logic was in several other places:
1. All the API controllers [already did this](https://github.com/PRX/feeder.prx.org/blob/main/app/controllers/api/podcasts_controller.rb#L9), calling `publish!` on the podcast in an after_action hook
- TODO: should the episode APIs be publishing the episode, instead of the podcast???
2. Feed images will [publish! the podcast](https://github.com/PRX/feeder.prx.org/blob/master/app/models/concerns/feed_image_file.rb#L24) when the status becomes complete after processing.
3. Episode contents (audio/video) will [publish! the episode](https://github.com/PRX/feeder.prx.org/blob/master/app/models/content.rb#L45) when the status becomes complete after processing.
4. Episode images …
> Podcast.publish! on change

- app/models/apple/api_waiting.rb
Reduce the output here, don't log all the waiting models' attributes.
> Log the remaining count

- app/models/apple/api.rb
- app/models/apple/config.rb
- app/models/apple/key.rb
- db/migrate/20230719174404_extract_credentials.rb
- db/schema.rb
- ops/bin/dump_db.sh
- test/factories/apple_config_factory.rb
- test/factories/apple_key_factory.rb
- test/models/apple/api_test.rb
- test/models/apple/config_test.rb
- test/models/apple/key_test.rb
- test/models/publishing_pipeline_state_test.rb
Closes #672 
This PR:
- extracts the key from the Apple::Config as an optional relation
- prevents the keys from being downloaded via the db dumping script.
> Extract the apple key out from the config

- app/models/apple/api.rb
- app/models/apple/podcast_delivery_file.rb
- test/models/apple/api_test.rb
closes https://github.com/PRX/feeder.prx.org/issues/680
Sets up a way to filter responses that have a 404 status.
In the case of polling, we just want to make sure we have the most up-to-date copy of the remote API state. If the delivery or delivery files are missing on the remote state, we can still use our local copies as sentinels e.g. in `Apple::PodcastContainer#delivery_settled?` and `Episode#apple_mark_for_reupload`
> Gone podcast delivery metadata

- app/models/apple/api.rb
- Don't print out Apple::Api instance variables by default
- More better exception messaging for missing keys
> Sets up Apple::Api inspect

- app/helpers/uploads_helper.rb
- app/javascript/controllers/polling_controller.js
- app/models/concerns/image_file.rb
- app/models/media_resource.rb
- app/views/episodes/media/_complete.html.erb
- app/views/episodes/media/_error.html.erb
- app/views/episodes/media/_media.html.erb
- app/views/episodes/media/_new.html.erb
- app/views/episodes/media/_processing.html.erb
- app/views/images/_error.html.erb
- app/views/images/_form.html.erb
- app/views/images/_meta.html.erb
- app/views/images/_modal.html.erb
- app/views/images/_new.html.erb
- app/views/images/_processing.html.erb
- config/locales/en.yml
- test/models/concerns/image_file_test.rb
- test/models/media_resource_test.rb
There was a bug in "retrying" audio/image processing.  Where it would (A) poll forever, and (B) submit dozens of processing jobs to retry instead of just one.
This fixes that - you can test by uploading with no worker running.  After ~100 seconds, you get a retry button that will fire off another Porter job.
> Retryable media

- app/helpers/embed_player_helper.rb
- app/models/episode.rb
- app/models/feed.rb
- app/models/podcast.rb
- test/models/episode_entry_handler_test.rb
Generates default links for podcasts/episodes.
So if you clear the Podcast `Homepage Link` or the episode `Episode URL` ... it will change it back to a play.prx.org `/listen` page.  (NOTE: those `/listen` links won't work for unpublished episodes).
> Generate default links

- app/models/apple/api_waiting.rb
- app/models/apple/episode.rb
- test/models/apple/api_waiting_test.rb
Seeing some timeouts on the audio asset processing.  For the small sample size we're pretty consistently bumping into the timeout.
This PR:
- Increases the timeouts to help more publishing runs complete without error
- Adds logging around the waiting/polling routine, so that we can characterise the distribution of the wait times.
> Increase audio asset state wait timeout

- app/models/apple/show.rb
- test/models/apple/show_test.rb
Since the API has a more stringent set of requirements on the required fields,
and we don't specifically need to do updates via the API,
we can skip the updates from the Apple::Publisher publish routine.
For now lets skip any updates to the show and figure out if we really need to do that via https://github.com/PRX/feeder.prx.org/issues/739
> Show skips updates via API

- app/jobs/publish_feed_job.rb
- app/models/podcast.rb
- app/models/publishing_pipeline_state.rb
- app/models/publishing_queue_item.rb
- test/jobs/publish_feed_job_test.rb
- test/models/podcast_test.rb
- test/models/publishing_pipeline_state_test.rb
- test/models/publishing_queue_item_test.rb
closes #714 
Sets up a retry mechanism that tests if the latest (most current) publishing pipeline has failed. If so, a new publishing publishing item is created and a new publishing pipeline is attempted.
> Retry publishing attempts

- app/models/concerns/advisory_locks.rb
This PR fixes a situation where we can get a stale read via AR query caching when we are probing of the current publishing item and state.
The uniqueness constraints here would prevent a duplicate state transition, but until https://github.com/PRX/feeder.prx.org/pull/752 the publishing attempts could land in an 'error' status because of those constraints.
> Disable AR query caching when grabbing the publishing lock 

- app/jobs/publish_feed_job.rb
- app/models/publishing_pipeline_state.rb
- test/jobs/publish_feed_job_test.rb
- test/models/publishing_pipeline_state_test.rb
Bug fix for the cases where:
- the job is started but there is no current publishing item to compare (which would itself be an error condition)
- the in-flight jobs via https://github.com/PRX/feeder.prx.org/pull/750 may not have had a pub item supplied as top level params.
> Guard for no current or scheduled publishing items

- app/workers/story_update_worker.rb
- test/workers/story_update_worker_test.rb
Seeing some 404s from CMS staging. The story unpublish (update) worker action is invoked after the story (CMS) and episode (Feeder) are deleted.
This PR guards against a gone story in the story update worker, logging a warning in that case.
> Handle unpublish (update) from deleted story

- app/jobs/start_publishing_pipeline_job.rb
- app/models/podcast.rb
- test/jobs/start_publishing_pipeline_job_test.rb
- test/models/podcast_test.rb
In the case where we have a transaction block calling `Podcast#publish!`, we can have dirty reads from other threads _outside_ of the transaction. This PR wraps the manipulation of the partitioned concurrency publishing queues in another async job invocation. This way, the database sessions outside of the authoring transactions can see the new state of the publishing queues.
> Extract the call to podcast publish to a job

- app/assets/stylesheets/shared/button.scss
- app/assets/stylesheets/shared/episode-card.scss
- app/assets/stylesheets/shared/header-nav.scss
- app/assets/stylesheets/shared/header.scss
- app/assets/stylesheets/shared/toast.scss
- app/views/episodes/index.html.erb
- Fixes Z-index issue in the ID App Switcher dropdown menu on Episode pages by adjusting custom z-index values to [bootstrap z-index variables](https://getbootstrap.com/docs/5.2/layout/z-index/)
EPISODE Landing page:
- Adds a container div to the episodes index page, so that when teasers get long, the episode columns don't get wildly wide
- Audio status badge should now always be present in the episode-card
> Fix z-index and other style bugs

- app/models/apple/podcast_delivery_file.rb
- test/models/apple/podcast_delivery_file_test.rb
Fixes a case where an episode was uploaded to the apple system, but the wait for linked asset state timed out.
Upon manual retry, the episode was marked for re-upload by deleting the delivery/delivery_files on the episode (`PodcastContainer#reset_source_file_metadata`). But since the _creation_  of delivery files changed with 520f2c9 (now based on Episode#needs_delivery?), the guard in the Apple::PodcastDeliveryFile class was blowing up -- expecting a delivery to be inplace.
This PR removes the assumption that a Apple::PodcastDelivery has to be in place in the delivery file sync routine. If the file is in the container, there is no need to redeliver -- in this case the episode simply needed to be marked as published.
> Fix: no delivery files are expected if there is no delivery

- app/views/feeds/_form_audio_format.html.erb
- app/views/imports/_form_status.html.erb
- config/locales/en.yml
Closes: #800 
- Removes empty help text on Feed type and feed URL
- Adds help text to "import podcast metadata"
> #800: Fix import help text

- app/assets/stylesheets/shared/form.scss
- app/views/episode_media/media/_new.html.erb
- app/views/images/_new.html.erb
- config/locales/en.yml
Closes: #768 
- This is a NO JS approach. It does most things except hover on the drop (which I think is okay.) If folks feel that is important we can add.
> Style drag n drop

- app/assets/stylesheets/app/uploads.scss
- app/views/episode_media/media/_complete.html.erb
- app/views/episode_media/media/_complete_audio.html.erb
- app/views/episode_media/media/_complete_video.html.erb
Closes #773 
I went and outdid myself here! I got video files playing back as video without affect audio uploads.
- Videos are responsive to the card width.
- Uses the default browser player.
To test:
> Playback video files as video

- app/controllers/podcasts_controller.rb
resolves #798 
masqueraded as Farski and was able to reproduce the mismatched podcast bug. it was an issue of the search filter used on each; the switcher does not use a text filter if nothing is input, whereas `podcasts#index` did not have that conditional. as a result, `podcasts#index` seemed to be filtering some podcasts even with an empty string, resulting in the mismatched podcast numbers.
> Add conditional on filter to default to base query

- app/models/concerns/episode_media.rb
- app/models/episode_story_handler.rb
- test/models/concerns/episode_media_test.rb
Fixes 2 recent prod issues:
1. An episode publishing to the feed before all of its files had processed (`episode.include_in_feed?` was true ... because `complete_media?` was also true)
2. CMS announced updates to a published episode briefly resulted in `complete_media?` returning false (it deleted the old media files without setting `replaced_at`).  Dovetail 500'd.
> Fixup episode feed-ready logic

- app/views/episodes/_form_main.html.erb
- app/views/podcasts/_form_main.html.erb
resolves #802 
the `div` wrappers solve the `is-changed` part of the bug. and it seems that in staging the other part of the bug no longer shows up, so it seems resolved for now.
> Add div wrapping to metadata and episode description fields

- app/models/tasks/copy_media_task.rb
- test/models/tasks/copy_media_task_test.rb
`BBC/audiowaveform/v1.x` wasn't working for flac files.  So switch to `PRX/FFprobe`, which handles more file types.
> Switch to PRX/FFprobe for audiowaveforms

- app/models/episode.rb
- app/models/feed.rb
- app/models/podcast.rb
Fixes #776.
Bit of a weird one - some of our `touch: true` associations weren't bubbling up to the parent records.  But only from UI updates - API and console updates worked fine.
Doing a bunch of QA, the places I saw it was:
- Updated a podcast -> settings description (a field on the `default_feed`) didn't touch the podcast
- Updating image fields (caption/credit) didn't touch parent feed+podcast or episode+podcast
- Sometimes, changing an image/media would update the podcast but _not_ the episode?
- Adding/removing images/media didn't always bubble up
Turns out, it was related to `accepts_nested_attributes_for`.  There was an issue in rails core, but that was solved several major versions ago.  The best suggestion I could find was [this …
> Fix form updated_at cascading

- app/models/tasks/copy_media_task.rb
Fixes #841.  Just needed the `-map_metadata 0` option.
Opted to keep metadata on all the sliced files, because, why not.
> Map metadata for sliced files

- app/models/episode.rb
- app/models/validators/bytesize_validator.rb
- test/models/episode_test.rb
Similar to https://github.com/PRX/publish.prx.org/pull/776 ... validate description HTML is <= 4000 bytes.  Only applies to UI entry (not API calls or RSS imports) for now.
> Description bytesize

- app/javascript/controllers/podcast_metrics_controller.js
Fixes #855.
Turns out, I just needed to debounce calling `chart.redraw()`.  Didn't bother to add any caching - Castle is returning these 40+ results real quick (IIRC, Castle has its own caching layer).
> Add slight debounce to redrawing chart

- app/assets/stylesheets/shared/episode-card.scss
- app/views/episodes/index.html.erb
Closes #885 
Since we now have filters and full width episode cards on the episodes index, I decided to change up the design of the cards on episodes very, very slightly to match the podcast card layout on the podcasts index.
> Clean up spacing and shadow usage on Episode cards

- app/helpers/uploads_helper.rb
- app/models/episode.rb
- app/views/episode_media/media/_new.html.erb
- test/models/episode_test.rb
So previously, if you changed an episode from "Upload single file" to "Upload multiple files", any existing contents we sliced from your single file will show up as the "multiple files".
This kind of does the inverse: if your "Upload multiple files" episode has a completed file in position 1, we preset that as the new file.  But - without saving it yet - clicking save will reprocess it.
Did notice we tend to get guid filenames doing these types of conversions - opened #874 to figure that out.
> Segment existing contents

- app/helpers/current_user_helper.rb
- test/helpers/current_user_helper_test.rb
The `current_user_app("metrics")` detection logic is broken.  This looks at the ID userinfo keys instead of url values, to detect if you have "metrics" / "augury" access.
> Fix app access detection

- app/assets/stylesheets/shared/form.scss
- app/controllers/feeds_controller.rb
- app/controllers/podcasts_controller.rb
- app/helpers/podcasts_helper.rb
- app/javascript/controllers/nested_select_controller.js
- app/models/concerns/feed_itunes_category.rb
- app/models/feed.rb
- app/views/feeds/_form_overrides.html.erb
- app/views/podcasts/_form_main.html.erb
- test/models/concerns/feed_itunes_category_test.rb
- test/models/feed_test.rb
- test/models/podcast_test.rb
Closes #890.
Allow setting multiple itunes categories/subcategories from the UI.
To make this work, I had to do a couple tricky things:
1. The Itunes Categories select is always sorted by the order you select them in.  So when you save, the top-most category in your RSS is the same as the leftmost one in this select.  NOT alphabetical.
2. The subcategories select updates every time you add a category.  To reflect all the subcategories under any of those categories.
3. Subcategories I just alphabetized.  We'll see if anyone cares how those are ordered, within the category.  I think it's most important to be able to pick which top-level category Apple sees.
> Multiple itunes categories

- app/models/apple/api.rb
Turns down the log level from error to warn for API request retries.
> Turn down retry errors

- app/models/concerns/publishing_status.rb
- app/views/episodes/_form_dropdate.html.erb
- test/models/concerns/publishing_status_test.rb
Fixes #902.
Two changes:
1. The episode dropdate form was previously hidden (behind that edit-pencil) when you had a validation error.  So it was hard to see why the save failed.  This shows the form automatically, if there's an error on the dropdate field.  (Try scheduling an episode with a past-dropdate to see).
2. IF the episode was draft but had a future-dropdate ... resets that to `Time.now`.  So changing the publishing status from Draft to Published should always "just work" now.
> Dropdate errors

- app/models/apple/podcast_delivery_file.rb
- app/models/apple/publisher.rb
- test/models/apple/publisher_test.rb
Fixes a case where the episode's podcast delivery files had processing errors, but because we were not using exception semantics (only logging errors),  we did not block the publishing of RSS.
This unites the exception handling / publishing blocking with the verification of the PodcastDeliveryFile processing status.
> Raise exception if there are any processing errors

- app/models/publishing_pipeline_state.rb
- test/models/publishing_pipeline_state_test.rb
Handles the case where the publishing pipeline cannot expire podcasts marked as deleted.
> Publishing Pipeline expire! can handle deleted podcasts

- app/controllers/api/auth/feeds_controller.rb
- app/models/authorization.rb
- test/controllers/api/auth/feeds_controller_test.rb
Feeds were not being filtered correctly.
> Filter auth feeds by authorized podcasts

- app/javascript/controllers/audio_breakpoints_controller.js
- app/views/layouts/_nav.html.erb
~Requires: https://github.com/PRX/internal/issues/1045 before merging~ DONE!
Closes: #780 
Does three things:
- Removes hyphens on `Pre-roll` and `Post-roll` in the audio segmenter. We don't use hyphens elsewhere describing those zones.
- Fixes teaser `line-height` on the podcast dashboard (unrelated)
- Adds mobile context menu to navigate apps
- Adds a link that will open an email address
> Feedback link + Mobile App Nav

- app/controllers/api/episodes_controller.rb
- app/controllers/concerns/api_published_range.rb
- app/controllers/concerns/api_updated_since.rb
- app/models/episode.rb
- test/controllers/api/episodes_controller_test.rb
Fixes #914.
Adds 2 params to the episodes APIs (both public and auth'd)...
- `?after=2023-11-14` filters by publishedAt `>=` (or releasedAt, for draft/scheduled episodes in the auth API)
- `?before=2023-11-14` filters by publishedAt `<` (exclusive)
Date strings are parsed with `DateTime.parse` - which is generally fairly permissive.
> Filter episodes by dropdate

- app/models/apple/episode.rb
- app/models/apple/publisher.rb
- app/models/episode.rb
- test/models/apple/episode_test.rb
- test/models/apple/publisher_test.rb
Fallout from https://github.com/PRX/feeder.prx.org/pull/853
Fixes up a case where old delivery records (Apple::PodcastDelivery, Apple::PodcastDeliveryFile) are not cleaned up upon retry of delivery.
In #853 we switched from using the podcast delivery/delivery files as sentinels for determining when the audio needed reuploaded to using a flag that's independent of any remote state (primarily because the delivery records are ephemeral in Apple's systems).  But, various places in the codebase assume that there is only a single set of delivery related models at a time.
This PR sets up a top level guard in the publishing routine that:
- filters for episodes that need delivery
- removes deliveries and delivery files for those episodes to-be-uploaded
> Clean up old delivery records upon retry

- app/controllers/imports_controller.rb
- app/helpers/uploads_helper.rb
- app/models/imports/podcast_rss_import.rb
- app/models/imports/podcast_timings_import.rb
- app/views/imports/_episode_import.html.erb
- app/views/imports/_episode_imports.html.erb
- app/views/imports/_form_rss.html.erb
- app/views/imports/_import_status.html.erb
- config/locales/en.yml
- test/models/imports/podcast_timings_import_test.rb
Fixes #912.  Fixes #913.
Also adds an option to _only_ import new episodes.  Useful because if you've imported RSS, then Timings, then RSS again (to get newest eps before a redirect)... you don't want that 2nd RSS import to blow away the timings.
> Import UI improvements

- app/controllers/api/podcasts_controller.rb
- app/models/concerns/episode_media.rb
- app/models/enclosure_url_builder.rb
- app/models/episode.rb
- test/models/concerns/episode_media_test.rb
- test/models/enclosure_url_builder_test.rb
- test/models/episode_entry_handler_test.rb
- test/representers/api/episode_representer_test.rb
Fixes #915.  This tackles leaving the `<enclosure>` in the RSS while we're waiting for the user to segment an Uncut file.
This does not tackle RSS/API metadata (duration, content type, file size) matching the exact files Dovetail Router is going to serve you.
> Include enclosures for replaced Uncut media

- app/views/podcasts/_form_main.html.erb
- config/locales/en.yml
- db/schema.rb
Closes #934
I'm open to more suggestions. As things come up.
> updating help text and labels

- app/controllers/episode_media_controller.rb
- app/models/tasks/copy_media_task.rb
- app/models/tasks/fix_media_task.rb
- test/factories/task_factory.rb
- test/models/tasks/copy_media_task_test.rb
- test/models/tasks/fix_media_task_test.rb
Fixes #941.  Fixes #940.  Fixes #942.
Porter is now returning a `"DurationDiscrepancy": 1234` milliseconds for audio (mp3s) where `mpck` and `ffprobe` disagree.
This PR takes a minimal-fix approach, and fires off a 2nd `Tasks::FixMediaTask` job when we detect a discrepancy > 500ms.  Which avoids running _everything_ through ffmpeg (slow), and storing basically duplicate copies of every original file.
> Fix bad mp3 durations

- app/models/concerns/episode_media.rb
- app/models/content.rb
- app/models/episode.rb
- app/models/media_resource.rb
- db/migrate/20240206213452_remove_media_resource_replaced_at.rb
- db/schema.rb
- test/models/concerns/episode_media_test.rb
- test/models/content_test.rb
- test/models/episode_test.rb
- test/models/media_resource_test.rb
- test/models/uncut_test.rb
Closes #835.
Now that we have the `media_versions` table, we don't need the `media_resources.replaced_at` field.
This removes it from the db, and just does a normal "mark for destruction" to set `deleted_at`.
> Remove media_resources.replaced_at

- app/assets/stylesheets/shared/trix-custom.scss
- app/models/episode.rb
- config/initializers/bootstrap_field_errors.rb
- lib/trix_editor.rb
Fix a couple issues with the trix editor and bootstrap-field-errors:
> Fix trix editor error messages

- app/models/apple/publisher.rb
- test/models/apple/publisher_test.rb
Fixes the case where a fully delivered episode is unpublished and then republished but left in a remote `DRAFTING` state. In this case the default `episodes_to_sync` params were being calculated prior to the unarchiving of an episode. Since `ARCHIVED` episodes are not published, the main delivery routine was skipping these unarchived episodes.
> Fix unarchived episodes published

- app/representers/api/episode_representer.rb
- app/representers/api/media_resource_representer.rb
- test/jobs/publish_feed_job_test.rb
- test/representers/api/episode_representer_test.rb
- test/representers/api/media_resource_representer_test.rb
Closes https://github.com/PRX/internal/issues/1080.
Finally deprecating them!
> Remove episode hrefs

- app/controllers/episodes_controller.rb
- app/views/episodes/_form_main.html.erb
Similar to #956.
Currently episodes coming from CMS Stories will have their [content attribute set](https://github.com/PRX/feeder.prx.org/blob/main/app/models/episode_story_handler.rb#L64) to the same as the description.  This is then rendered into the feed as `<content:encoded>`.
But when a show moves to the Feeder UI, the `ep.content` field gets stuck into a stale/old state.  This PR just nils out the field, so the `<content:encoded>` tag disappears.  Which shouldn't be a problem - it's only present on full episodes, and basically always redundant with `<description>`.
> Nil out episode contents

- app/helpers/episodes_helper.rb
- app/models/concerns/apple_delivery.rb
- app/views/episodes/_form_status.html.erb
- config/locales/en.yml
Implements part of #632 to display the apple publishing  status on the episode
> Add Apple publish status

- app/jobs/publish_feed_job.rb
- app/models/apple/config.rb
- app/models/feed.rb
- app/models/podcast.rb
- db/migrate/20240410212602_simplify_apple_config_foreign_keys.rb
- db/schema.rb
- test/factories/apple_config_factory.rb
- test/jobs/publish_apple_job_test.rb
- test/jobs/publish_feed_job_test.rb
- test/models/apple/config_test.rb
- test/models/apple/episode_test.rb
- test/models/apple/podcast_container_test.rb
- test/models/apple/podcast_delivery_file_test.rb
- test/models/apple/publisher_test.rb
- test/models/apple/show_test.rb
- test/models/feed_test.rb
- test/models/imports/podcast_rss_import_test.rb
- test/models/publishing_pipeline_state_test.rb
Our Apple::Config schema is fighting a bit with the formbuilder/UI.  Since it shows up on the _private_ Feed form UI.  But only the `public_feed has_one :apple_config`.  And there are 3 foreign keys to populate/validate.
This simplifies down to a single assocation: `private_feed has_one :apple_config`.  And then I alias/delegate everything else when possible, to keep interfaces the same.
Should definitely QA this one carefully.  Because it makes me nervous!
> Apple::Config only belongs to the private feed

- app/views/episodes/_existing_drafts.html.erb
- app/views/episodes/new.html.erb
- config/locales/en.yml
Closes #992 
Adds a modal that warns producers there's an existing draft and they should use that.
> Warn producers when new draft episodes exist

- app/javascript/controllers/disable_controller.js
- app/javascript/controllers/upload_controller.js
- app/views/episode_media/media/_new.html.erb
- app/views/episode_media/media/_non_mp3_warning.html.erb
- config/locales/en.yml
Fixes #1002.
When you upload a non-mp3 (really, a non-`audio/mpeg` format) file and have no `default_feed.audio_format`... we warn you.  Exact wording TBD.
Pretty easy to game the system by changing your `.wav` file extension.  But I think this is enough to prevent accidentally publishing WAVs into the public RSS.
> Non-mp3s in default feed

- app/controllers/application_controller.rb
- app/controllers/episode_media_controller.rb
- app/controllers/episodes_controller.rb
- app/controllers/feeds_controller.rb
- app/controllers/podcast_engagement_controller.rb
- app/controllers/podcasts_controller.rb
- app/javascript/controllers/toggle_value_controller.js
- app/models/application_record.rb
- app/views/episode_media/_form.html.erb
- app/views/episode_media/_form_status.html.erb
- app/views/episodes/_form.html.erb
- app/views/episodes/_form_status.html.erb
- app/views/feeds/_form.html.erb
- app/views/feeds/_form_status.html.erb
- app/views/layouts/_stale_record_field.html.erb
- app/views/layouts/_stale_record_modal.html.erb
- app/views/podcast_engagement/_form.html.erb
- app/views/podcast_engagement/_form_status.html.erb
- app/views/podcasts/_form.html.erb
- app/views/podcasts/_form_status.html.erb
- config/locales/en.yml
- db/migrate/20240424214558_add_locking_columns.rb
- db/schema.rb
- test/controllers/episodes_controller_test.rb
- test/controllers/feeds_controller_test.rb
- test/controllers/podcasts_controller_test.rb
Closes #1000.
Adds optimistic locking to _UI updates only_.  This avoids locking a bunch of browser-forms every time an async worker callback touches a record.  (Turns out, rails `lock_version`s bubble up, along with the updated_at timestamps we use to break caches).
If a user updates a form and it's been edited by someone else in the interim, throw up a warning.  Which lets them either discard their changes or manually confirm they want to overwrite.
Added to the pages:
> Optimistic locking

- app/controllers/episode_media_controller.rb
- app/controllers/episodes_controller.rb
- app/controllers/feeds_controller.rb
- app/controllers/podcast_engagement_controller.rb
- app/controllers/podcasts_controller.rb
- app/javascript/controllers/toggle_value_controller.js
- app/models/application_record.rb
- app/views/episode_media/_form.html.erb
- app/views/episode_media/_form_status.html.erb
- app/views/episodes/_form.html.erb
- app/views/episodes/_form_status.html.erb
- app/views/feeds/_form.html.erb
- app/views/feeds/_form_status.html.erb
- app/views/layouts/_stale_record_field.html.erb
- app/views/layouts/_stale_record_modal.html.erb
- app/views/podcast_engagement/_form.html.erb
- app/views/podcast_engagement/_form_status.html.erb
- app/views/podcasts/_form.html.erb
- app/views/podcasts/_form_status.html.erb
- config/locales/en.yml
- db/migrate/20240424214558_add_locking_columns.rb
- db/schema.rb
- test/controllers/episodes_controller_test.rb
- test/controllers/feeds_controller_test.rb
- test/controllers/podcasts_controller_test.rb
Redoing #1006.
We were hitting issues in prod where users could not upload files.  The server was throwing `:conflict`s, but failing to render the modal.  Plus nobody else had edited the object in the background.
This appeared to be a combination of:
1. The default `lock_version` for these tables in the db is `NULL`.  Which rails casts to `0` - but for some reason this was tripping/failing the [constraint](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/locking/optimistic.rb#L108) rails uses when incrementing the column.
2. Saving a nested form object (such as images/audio) _without_ changing anything on the parent Podcast/Feed/Episode.
Setting a default of `0` in the migration seems to resolve the issue for me.  That's the only change I've made to #1006.
> Cautiously optimistic locking (attempt 2)

- app/models/apple/episode.rb
- app/models/enclosure_url_builder.rb
- test/models/apple/episode_test.rb
- test/models/enclosure_url_builder_test.rb
Delegated delivery:
- Removes the `noImp` query param to enable impression logging in Dovetail
- in conjunction with https://github.com/PRX/prx-podagent/pull/43 to enable filtering as a bot
> Remove the noImp decorator in enclosure builder

- app/models/application_record.rb
Whoops - every model was sharing the same error message aliases.
> Make sure parent/child classes don't all share the same aliases

- app/controllers/api/episodes_controller.rb
- app/models/concerns/episode_has_feeds.rb
- app/models/episode.rb
- app/models/feed.rb
- app/representers/api/auth/episode_representer.rb
- test/controllers/api/episodes_controller_test.rb
- test/models/concerns/episode_has_feeds_test.rb
- test/models/concerns/release_episodes_test.rb
- test/models/episode_test.rb
- test/models/feed_test.rb
After #1019.
Closes https://github.com/PRX/internal/issues/1104.  Should QA that castle API scraping still works.  But I think it will.
```
{
feedSlugs: ["default", "apple-sub-feed", "some-other-feed"]
}
```
Fallout: apply display_episodes_count to API results.
> API episode feeds

- app/models/concerns/release_episodes.rb
- app/models/podcast.rb
- app/models/podcast_import.rb
- db/migrate/20240821135645_add_locked_until.rb
- db/schema.rb
- test/models/concerns/release_episodes_test.rb
- test/models/podcast_import_test.rb
We've been getting some large (multiple thousands) RSS imports lately.
After #1066 and #1067, we seem to get through the initial "import" without clogging the workers.
But now, the thousands of Porter callbacks seem to be clogging the publish queue.  Yesterday, I ended up setting `locked = true` on a Podcast and terminating hundreds of `SELECT pg_advisory_lock(1, 9999)` statements in postgres before the workers unblocked (they were processing < 1 job a minute... and maybe just timing out?)
This works around any contention in that publishing queue advisory lock, by delaying unlocking the podcast for 1 minute per 150 episodes.  The `ReleaseEpisodesJob` cron will pick the Podcast up and call `.publish!` once we get past the `podcast.locked_until` timestamp.
> Lock podcast until timestamp

- app/assets/stylesheets/shared/reboot.scss
Change selector for `<a>` tag reboot styles to apply to those not being styled by a class. This will prevent this reset from bleeding into styled anchors like menu item links.
> fix(styles): anchor reboot selector

- app/assets/stylesheets/shared/form.scss
when we merged #1087 we overlooked the help icons which contains an underline. This fixes it forever. 
(I'll update in Augury too)
> HOTFIX: Remove help icon underlines

- app/views/podcast_planner/_form_draft.html.erb
resolves #1095 
This PR resolves the issue of the submit button on the Planner not disabling fully after submit, causing request issues. The solution re-enables turbo on the submit button, but makes it target the whole page (`_top`) instead of just within the context of its turbo frame.
> Re-enable turbo on the submit but direct it to the whole page

- app/views/feeds/_form_main.html.erb
resolves #1096 
This PR hides the Episode Offset field from the default feed view. This is because we don't want a user to have the option of setting an offset for the default feed. The ticket suggests possibly adding a validation, but [one already exists](https://github.com/PRX/feeder.prx.org/blob/d269a3d51c2c976a61232b1909a22eaa31ede776/app/models/feed.rb#L51) and the [testing for it](https://github.com/PRX/feeder.prx.org/blob/d269a3d51c2c976a61232b1909a22eaa31ede776/test/models/feed_test.rb#L194) seems logical and no additions seem to be needed.
> Hide episode offset field from default feed view

- app/views/feeds/_form_audio_format.html.erb
resolves #1117 
This PR sets a default value for the audio format dropdowns. The issue was that with no default, the first choice in options is selected and it is the lowest quality option (sorting low to high). Adding a default value with a higher quality intends to reduce user error unintentionally selecting low quality options.
> Add default values to the audio format selects

- app/views/layouts/_subnav.html.erb
resolves #1103 
This PR addresses the issue of leaked authorized info of a podcast. Previously, a user could still see the navbar of a podcast that they did not have authorization for, and therefore could view the title of the podcast seen in the podcast switcher partial. This PR wraps the subnav in a policy in order prevent access to users who do not have view access to the selected podcast. Because the subnav is used across many other views, this should be consistent any layout that utilizes the subnav, including the `episodes` and `feeds` views.
> Wrap subnav with authorization policy

- app/views/episode_media/media/_media.html.erb
- app/views/episode_media/media/_processing.html.erb
- app/views/episode_transcripts/transcripts/_form.html.erb
- app/views/episode_transcripts/transcripts/_processing.html.erb
- app/views/images/_form.html.erb
- app/views/images/_processing.html.erb
- config/locales/en.yml
resolves #1094 
This PR solves a "hidden timeout" issue users were experiencing, by rendering a "still processing" message for "stalled" uploads. The solution i chose to solve for this was to opt for rendering the `_processing` partial instead of the `_error` partial for the `upload_stalled?` user conditional flow. I did this because i saw that the only difference between `upload_processing?` and `upload_stalled?` was the `retryable` condition. Therefore, a "stalled" upload should still be processing. A side benefit to using the `_processing` partial is that it continually polls the server, whereas the `_error` partial does not; if a "stalled" upload eventually completed, the `_error` view wouldn't refresh on its own to a `_complete` view, whereas the `_processing` view does.
Within the …
> Render processing view for stalled uploads

- app/models/podcast.rb
- app/views/podcasts/show.rss.builder
- db/migrate/20240928150204_add_guid_to_podcasts.rb
- db/schema.rb
- test/models/podcast_test.rb
> Add podcasts guid, set by uuidv5, add to rss

- app/models/feeds/apple_subscription.rb
- app/views/feeds/_form.html.erb
- app/views/feeds/_form_apple_config.html.erb
- config/locales/en.yml
- test/models/feed/apple_subscription_test.rb
Turns out, Apple relaxed their requirements for paid subscribers.
This adds a utility `.guess_audio_format` to check the default_feed and episodes for the highest quality mp3 format they use.
Also closes #1121 .
> Use mp3 instead of flac for apple feeds

- app/models/uncut.rb
- test/models/uncut_test.rb
resolves #1073 
This PR adds a validation for the `duration` attribute of the `Uncut` model. There was an issue in which Porter somehow returned a nil duration in an `Inspect` task, and caused a bug in the audio segmenter that utilizes the `duration` attribute. Validation and testing was added to the `Uncut` model specifically (instead of `MediaResource` or `Content`) because we want to address the issue in the audio segmenter, and not for any `"video"` media at this time.
> Add duration validation and test

- app/controllers/api/episodes_controller.rb
- app/controllers/api/podcasts_controller.rb
- config/routes.rb
Adds endpoints to lookup by `prx_uri`:
```
/api/v1/comatose/series/1234
/api/v1/comatose/stories/5678
```
> API endpoints for old CMS data

- app/controllers/feeds_controller.rb
- app/helpers/podcasts_helper.rb
- app/views/feeds/_form_main.html.erb
- app/views/podcasts/show.rss.builder
- config/locales/en.yml
- db/migrate/20241116011452_add_footer_to_feeds.rb
- db/schema.rb
- test/helpers/podcasts_helper_test.rb
> Episode description footer

- lib/remove_chartable.rb
for review!
I ran it against prod data in debug mode, and it looks like it works on all the prefix values.
fixed #1160
> Add class to remove chartable prefix

- app/models/apple/podcast_delivery.rb
- db/migrate/20241105154932_drop_unused_podcast_container_cols.rb
- db/schema.rb
Removes state columns that were superseded by the Apple::EpisodeDeliveryStatus model (https://github.com/PRX/feeder.prx.org/pull/901)
> Remove Unused Columns

- app/models/task.rb
- app/models/tasks/copy_media_task.rb
- app/models/tasks/fix_media_task.rb
- test/models/task_test.rb
- test/models/tasks/copy_media_task_test.rb
Fixes #1109.
Requires https://github.com/PRX/Porter/pull/164.
When a VBR file is uploaded, transcode it to CBR by running it back through Porter/ffmpeg.
Can be a bit slow, but better than having a misleading segmenter wavform.
> Transcode VBR mp3 files to CBR

- app/controllers/episodes_controller.rb
- app/helpers/embed_player_helper.rb
- app/views/episodes/_episode_filters.html.erb
- config/locales/en.yml
- config/routes.rb
Fixes #1175.
Simple export-episodes-to-CSV button/route.  Threw a few maybe-useful things in there.  We should get some feedback and see what folks actually want (there are many many fields we could add).
> Export episodes to CSV

- app/models/publishing_pipeline_state.rb
- app/models/publishing_queue_item.rb
- test/models/publishing_pipeline_state_test.rb
- test/models/publishing_queue_item_test.rb
Closes https://github.com/PRX/feeder.prx.org/issues/1134
This includes the intermediate `error_apple` in the list of retryable error states. Prior to this, we had only considered _terminal_ error states. With this PR, we will retry publishing pipelines having intermediate `error_apple` states and terminal `complete` (success) states.
> Retry on error_apple non-terminal error

- app/assets/stylesheets/shared/trix-custom.scss
> Normal font weight for trix editor anchor text

- app/models/feed.rb
- app/models/feeds/megaphone_feed.rb
- app/models/megaphone/episode.rb
- app/models/megaphone/podcast.rb
- app/representers/api/auth/feed_representer.rb
- test/models/megaphone/podcast_test.rb
- test/representers/api/auth/feed_representer_test.rb
> Fixes from testing megaphone in staging

- app/models/sync_log.rb
- test/models/sync_log_test.rb
Closes [#1212](https://github.com/PRX/feeder.prx.org/issues/1212)
Makes sure that the sync log's timestamp is updated with each "sync" of the remote state. Helpful for debugging.
> Touches the updated_at timestamp with each sync

- app/models/apple/publisher.rb
- test/models/apple/publisher_test.rb
Fixes an issue where an episode is marked drafting async via the podcasts connect API and then is stuck in redelivery because of missing remote podcasts delivery file resources (which are typically pruned after a month).
This PR builds on #1150 by guarding against re-delivery (probing for file processing, waiting on asset state) for episodes that have simply had their drafting status toggled. This leverages the new top level _uploaded_ and _delivered_ state that landed with #1150 (merged via the megaphone branch), and makes sure that for episodes marked uploaded and delivered that no attempt to "re-deliver" is made.
> Guard against delivering already delivered episodes

- app/javascript/controllers/upload_controller.js
- app/models/media_resource.rb
- app/views/episode_media/media/_new.html.erb
- config/locales/en.yml
Saw a prod issue where someone uploaded a video larger than our postgres 4-byte integer column `file_size` could hold.  (Max is 2147483647... which is like ~2GB).
This PR restricts uploads to 1GB, which you'd think would be plenty.  Largest file in prod is just under 1GB right now.
> Restrict uploads to 1GB

- app/controllers/feeds_controller.rb
- app/models/feeds/megaphone_feed.rb
- app/models/megaphone/api.rb
- app/models/megaphone/config.rb
- app/models/megaphone/model.rb
- app/models/megaphone/organization_tag.rb
- app/models/megaphone/podcast.rb
- app/views/feeds/_form_megaphone_config.html.erb
- db/migrate/20250503181540_add_organization_id_to_megaphone_configs.rb
- db/migrate/20250503194609_add_advertising_tags_to_megaphone_configs.rb
- db/schema.rb
- test/factories/megaphone_config_factory.rb
- test/models/megaphone/api_test.rb
- test/models/megaphone/config_test.rb
- test/models/megaphone/organization_tag_test.rb
> Set from megaphone podcast ad tags from organization tag options

- app/models/megaphone/cuepoint.rb
- test/models/megaphone/cuepoint_test.rb
- test/models/megaphone/episode_test.rb
this is a limited fix, another option would be to change the behavior of BigDecimal as_json to always convert to_f rather than just affecting these specific attributes in this one model
and another option is to use Oj for this, which has an explicit option for bigdecimal_as_decimal https://www.ohler.com/oj/doc/Oj.html
> Start and end times for cuepoints must be floats in json

- app/controllers/api/episodes_controller.rb
Fixes #1262.
Use the [find_base](https://github.com/PRX/hal_api-rails/blob/main/lib/hal_api/controller/resources.rb#L82) method instead of search all episodes for a guid.
> Filter episode guids by podcast

- app/assets/stylesheets/app/calendar.scss
closes #1265 
- the global styles table striping classes overrode the custom context backgrounds for calendar drafts
Fixed:
> HOTFIX: planning calendar colors

- app/models/media_resource.rb
- test/models/media_resource_test.rb
Was seeing an API error, where the original_url of media got set to `"<br/>"` (it was from a bad RSS import).  And URI.parse was erroring out.
> Handle non-parseable urls

- app/models/concerns/episode_media.rb
- app/models/media_version.rb
Rely on aliases instead of using different SQL for index/show.
In other words... this works for both `Episode.find(...).latest_media_version` and `Episode.limit(100).includes(:latest_media_version)`.
> Even better latest_media_version query
