app/models/task.rb

Fixer jobs can have retry logic, need to add that to the message

Add 12 retries, 5 minutes apart

---

app/models/episode_entry_handler.rb
test/models/episode_entry_handler_test.rb

Previously, when comparing an updated rss feed entry, the entire enclosure url was checked against the last saved enclosure url (saved in the existing media_resource.original_url attribute).
However, sometimes the only change is a prefix, such as the podtrac url, or cdn, and not the actual audio.
To prevent those being false positives for audio changes, only compare the filename (i.e. url path after the last slash) of the url, not the entire url.

Compare enclosure/content url filename against original, not the entire url

---

app/controllers/api/auth/episodes_controller.rb
app/controllers/api/auth/podcasts_controller.rb
app/controllers/api/authorizations_controller.rb
app/controllers/api/podcasts_controller.rb
app/controllers/concerns/api_authenticated.rb
app/models/api.rb
app/models/authorization.rb
app/models/base_model.rb
app/models/episode.rb
app/models/feed_image.rb
app/models/itunes_category.rb
app/models/itunes_image.rb
app/models/media_resource.rb
app/models/podcast.rb
app/models/task.rb
app/representers/api/authorization_representer.rb
config/routes.rb
db/migrate/20161121171637_add_podcasts_published_at.rb
db/schema.rb
test/controllers/api/auth/episodes_controller_test.rb
test/controllers/api/auth/podcasts_controller_test.rb
test/controllers/api/authorizations_controller_test.rb
test/factories/episode_factory.rb
test/factories/podcast_factory.rb
test/models/api_test.rb
test/models/authorization_test.rb
test/representers/api/authorization_representer_test.rb
test/representers/api_representer_test.rb
test/test_helper.rb

Authenticated urls

---

app/controllers/api/auth/episodes_controller.rb
app/controllers/api/base_controller.rb
app/controllers/api/episodes_controller.rb
app/models/episode.rb
app/models/feed_image.rb
app/models/itunes_category.rb
app/models/itunes_image.rb
app/models/media_resource.rb
app/representers/api/podcast_representer.rb
lib/prx_access.rb
test/controllers/api/episodes_controller_test.rb
test/lib/prx_access_test.rb

Return 410

---

app/models/itunes_category_validator.rb

https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12

Update itunes categories

---

app/models/episode.rb
app/models/podcast.rb
test/controllers/api/podcasts_controller_test.rb

Destroy dependents to trigger touch on parent podcast or episode

---

app/controllers/api/base_controller.rb
test/controllers/api/podcasts_controller_test.rb

Fix authorization error API response

---

app/models/episode_story_handler.rb
config/initializers/config_env.rb
test/fixtures/prx_story_all.json
test/models/episode_story_handler_test.rb
test/models/media_resource_test.rb

Fix broken urls

---

app/views/podcasts/show.rss.builder

Allow for case when neither story nor series has image.

---

app/models/episode.rb
test/models/episode_test.rb
test/representers/episode_representer_test.rb

Use underscore instead of colon as a delimiter

---

app/views/podcasts/show.rss.builder
test/integration/podcast_request_test.rb

Correctly set episode itunes|author 

---

app/models/episode.rb
app/models/podcast.rb
test/models/podcast_test.rb

Don't unpublish a podcast based on episode published_at

---

app/jobs/story_update_job.rb
app/models/episode_story_handler.rb
test/fixtures/prx_invalid_story_updates.json
test/fixtures/prx_story_updates.json
test/jobs/story_update_job_test.rb

Reject invalid story updates and publishes

---

app/helpers/podcasts_helper.rb
app/views/podcasts/show.rss.builder
lib/prx_access.rb
test/integration/podcast_request_test.rb

fix how author appears in the feed

---

app/models/tasks/copy_image_task.rb
test/models/tasks/copy_image_task_test.rb

Change the image fixer task type

---

app/helpers/podcasts_helper.rb
app/views/podcasts/show.rss.builder
test/integration/podcast_request_test.rb

Add defaults for author and owner

---

db/migrate/20170223114125_create_episode_images.rb

limit inserts to episodes where the image url is not null

---

app/models/episode.rb
app/models/podcast.rb
app/views/podcasts/show.rss.builder
test/integration/podcast_request_test.rb

Feed import fixes

---

app/models/episode_entry_handler.rb
db/migrate/20160216190727_refactor_images.rb

Fix podcast images insert, comments

---

app/models/episode_story_handler.rb
test/fixtures/prx_story_all.json
test/models/episode_story_handler_test.rb

relies on https://github.com/PRX/cms.prx.org/pull/311

Set the episode explicit value from the audio version

---

Dockerfile
bin/application

* install secrets in dockerfile
* load secrets in bin/application

Add aws-secrets

---

app/views/podcasts/show.rss.builder

check for the author before trying to get the author name

handle when there is no author

---

.prxci
bin/application
docker-compose-ci.yml

Enable CI builds

---

app/models/episode.rb
test/controllers/api/episodes_controller_test.rb

Check if file name or the path preceding it have changed

---

Dockerfile
Gemfile
Gemfile.lock
app/jobs/release_episodes_job.rb
app/models/episode.rb
bin/application
config/initializers/say_when.rb
config/initializers/shoryuken.rb
db/migrate/20170621213139_create_say_when_tables.rb
db/schema.rb
test/jobs/release_episodes_job_test.rb
test/models/episode_entry_handler_test.rb

* Add say_when gem
* Init scheduled episode release in say_when init
* Move episode release method to the `Episode` resource

Add say_when to release episodes

---

app/models/episode.rb
test/models/episode_test.rb

Better removal of illegal characters from keyword_xid

---

app/models/concerns/text_sanitizer.rb
test/models/concerns/text_sanitizer_test.rb
test/models/episode_test.rb

Allow ampersands

---

app/controllers/api/auth/episodes_controller.rb
app/controllers/api/episodes_controller.rb
test/controllers/api/auth/episodes_controller_test.rb
test/controllers/api/episodes_controller_test.rb

Filter out pre-published episodes

---

app/controllers/podcasts_controller.rb
app/models/podcast.rb
app/representers/api/podcast_representer.rb
db/migrate/20180214144148_add_frozen_to_podcasts.rb
db/migrate/20180214150849_add_locked_to_podcasts.rb
db/schema.rb
test/controllers/podcasts_controller_test.rb
test/models/podcast_test.rb

Lock feeds

---

Guardfile
app/jobs/application_job.rb
app/jobs/feed_entry_update_job.rb
app/jobs/release_episodes_job.rb
app/jobs/series_update_job.rb
app/jobs/story_update_job.rb
docker-compose.yml

Log job errors to newrelic 

---

app/models/episode_story_handler.rb
test/jobs/story_update_job_test.rb

User public uri for prx story, not with authorization in it

---

app/controllers/api/episodes_controller.rb
app/controllers/api/podcasts_controller.rb
app/controllers/concerns/api_updated_since.rb
test/controllers/concerns/api_updated_since_test.rb

Query param to filter/sort since a datetime.

Query for podcasts/episodes updated since a date

---

app/jobs/story_update_job.rb
test/fixtures/prx_story_deleted.json
test/jobs/story_update_job_test.rb

Delete episodes for deleted stories

---

app/jobs/publish_feed_job.rb

```
TypeError: no implicit conversion of Fixnum into String
```

Fix podcast path int

---

Dockerfile
app/models/episode.rb
app/representers/api/episode_representer.rb
test/representers/api/episode_representer_test.rb

Don't throw 500s for episodes without a podcast.

Fix podcast-less episodes

---

Gemfile
Gemfile.lock

Upgrade ruby to support a new version of PRX auth gems. Fix security warnings.

Security patches

---

app/models/itunes_category_validator.rb
db/migrate/20190724191053_update_itunes_categories.rb
db/schema.rb
test/factories/itunes_category_factory.rb
test/models/podcast_feed_handler_test.rb
test/representers/api/podcast_representer_test.rb

Updates categories per https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12

updates iTunes Categories

---

Gemfile
Gemfile.lock
app/models/authorization.rb
config/application.rb
config/initializers/prx_auth.rb
test/test_helper.rb

Upgrade PrxAuth::Rails gem

---

app/jobs/publish_feed_job.rb
app/models/concerns/porter_encoder.rb
test/models/concerns/porter_encoder_test.rb

Stop setting public-read ACLs

---

app/models/authorization.rb
app/models/episode.rb
app/policies/episode_policy.rb
app/policies/podcast_policy.rb
config/initializers/prx_auth.rb
test/controllers/api/auth/episodes_controller_test.rb
test/controllers/api/auth/podcasts_controller_test.rb
test/controllers/api/authorizations_controller_test.rb
test/controllers/api/episodes_controller_test.rb
test/controllers/api/podcasts_controller_test.rb
test/models/authorization_test.rb
test/policies/episode_policy_test.rb
test/policies/podcast_policy_test.rb
test/representers/api/authorization_representer_test.rb

Reverts PRX/feeder.prx.org#363

Revert "Scope-based policies"

---

app/models/authorization.rb
app/models/episode.rb
app/policies/episode_policy.rb
app/policies/podcast_policy.rb
config/initializers/prx_auth.rb
test/controllers/api/auth/episodes_controller_test.rb
test/controllers/api/auth/podcasts_controller_test.rb
test/controllers/api/authorizations_controller_test.rb
test/controllers/api/episodes_controller_test.rb
test/controllers/api/podcasts_controller_test.rb
test/models/authorization_test.rb
test/policies/episode_policy_test.rb
test/policies/podcast_policy_test.rb
test/representers/api/authorization_representer_test.rb

Reverts PRX/feeder.prx.org#364
Which actually just brings us back to #363.

Revert "Revert "Scope-based policies""

---

app/models/episode.rb
app/representers/api/episode_representer.rb
test/representers/api/episode_representer_test.rb

Add the episode's podcast feed url to the links in the API response

Episode podcast feed

---

app/representers/api/auth/feed_representer.rb
app/representers/api/podcast_representer.rb
app/views/podcasts/show.rss.builder
db/migrate/20220928174716_revise_payment_pointer.rb
db/schema.rb
test/factories/feed_factory.rb
test/factories/podcast_factory.rb
test/models/feed_builder_test.rb

[] Removed existing `payment_pointer` from column
[] Added new fields to `podcasts` and `feeds` tables with new parameters for payment options

Revised Payment Pointer

---

app/models/episode.rb
test/models/episode_test.rb

Resolves #444 
Validates original guids

validates original guid uniqueness

---

app/views/podcasts/show.rss.builder
test/models/feed_builder_test.rb

Closes #450 
Added donation url to RSS builder.

Add donation url to rss

---

app/controllers/api/episodes_controller.rb
app/models/episode.rb
app/representers/api/api_representer.rb
app/representers/api/auth/podcast_representer.rb
app/representers/api/authorization_representer.rb
app/representers/api/podcast_representer.rb
config/routes.rb
test/controllers/api/episodes_controller_test.rb
test/models/episode_test.rb

Reverts PRX/feeder.prx.org#494.
I've broken caching!

Revert "Find by item guid"

---

app/controllers/api/episodes_controller.rb
app/models/episode.rb
app/representers/api/api_representer.rb
app/representers/api/auth/podcast_representer.rb
app/representers/api/authorization_representer.rb
app/representers/api/podcast_representer.rb
config/routes.rb
test/controllers/api/episodes_controller_test.rb
test/models/episode_test.rb

🚧 WIP.
But this time... don't break caching.

Revert "Revert "Find by item guid""

---

app/controllers/api/episodes_controller.rb

Redirect with episode guid, not id

---

Gemfile

Gemfile was bothering me a bit.
Made an attempt to group gems, and alphabetize within those groups.
Open to feedback!

Group and order gems

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/card.scss
app/assets/stylesheets/shared/bootstrap-variables.scss
app/assets/stylesheets/shared/card.scss
app/assets/stylesheets/shared/layout.scss
app/views/fake/index.html.erb
app/views/fake/show.html.erb

Adding a fully styled card with a lot of different options that will be used in some cards, but not all. 
Is it too heavy on bootstrap classes?

Card example

---

Gemfile
Gemfile.lock
app/controllers/api/base_controller.rb
app/controllers/application_controller.rb
app/controllers/feeds_controller.rb
app/controllers/podcasts_controller.rb
app/views/layouts/_nav.html.erb
app/views/layouts/_subnav.html.erb
config/initializers/prx_auth.rb
config/initializers/session_store.rb
config/routes.rb
db/migrate/20230126214239_add_sessions_table.rb
db/schema.rb

Copying code from Augury, plus a few other fixups for Rails 7.

Authenticate with ID

---

app/assets/stylesheets/shared/header.scss
app/helpers/current_user_helper.rb
app/views/layouts/_nav.html.erb
config/locales/en.yml
test/helpers/current_user_helper_test.rb

Closes #504.
Wires up actual ID app data into the user dropdown.  And adds translations for everything.
I also opted to drop the big list of apps in the dropdown, and just added "Metrics" up top for now.

Wire up nav

---

app/assets/stylesheets/shared/header.scss
app/views/layouts/_nav.html.erb

- Fixes issue when there's a really long podcast name in the podcast switcher and dropdown menu (the menu will expand)
- Cleans up responsive styles quite a bit.
To Review:
- Run the server
- Open code inspector and confirm the nav just looks better at all screensizes.

Nav and Subnav Style clean up

---

app/assets/stylesheets/shared/form.scss
app/controllers/podcasts_controller.rb
app/helpers/accounts_helper.rb
app/helpers/podcasts_helper.rb
app/javascript/controllers/dynamic_form_controller.js
app/javascript/controllers/toggle_field_controller.js
app/models/itunes_category.rb
app/models/podcast.rb
app/models/validators/http_url_validator.rb
app/models/validators/itunes_category_validator.rb
app/policies/podcast_policy.rb
app/views/layouts/application.html.erb
app/views/podcasts/_form.html.erb
app/views/podcasts/_form_feed_image.html.erb
app/views/podcasts/_form_itunes_image.html.erb
app/views/podcasts/_form_main.html.erb
app/views/podcasts/_form_status.html.erb
app/views/podcasts/_tabs.html.erb
app/views/podcasts/edit.html.erb
config/locales/en.yml
test/controllers/api/podcasts_controller_test.rb
test/controllers/podcasts_controller_test.rb
test/factories/itunes_image_factory.rb
test/models/podcast_test.rb
test/representers/api/podcast_representer_test.rb
test/test_helper.rb

Closes #509.  Figure out impact on Publish/CMS before merging.

Edit podcast metadata

---

app/assets/stylesheets/card.scss
app/assets/stylesheets/shared/form.scss
app/assets/stylesheets/shared/layout.scss
app/assets/stylesheets/shared/tabs.scss
app/javascript/controllers/tooltip_controller.js
app/views/layouts/application.html.erb
app/views/podcasts/_form_main.html.erb
config/locales/en.yml

Styling for Podcast Metadata tab (and some help text)

---

app/assets/stylesheets/shared/card.scss
app/views/episodes/_form.html.erb
app/views/episodes/_form_audio.html.erb
app/views/episodes/_form_distribution.html.erb
app/views/episodes/_form_image.html.erb
app/views/episodes/_form_main.html.erb
app/views/episodes/_form_status.html.erb
app/views/episodes/_form_tags.html.erb
app/views/episodes/index.html.erb
config/locales/en.yml

- Adds help text throughout the episode form
- Includes some minor styling adjustments to episodes

Add help text to Episode Form

---

app/representers/api/episode_representer.rb
test/representers/api/episode_representer_test.rb

Adds podcast title to episode api response

---

app/jobs/episode_import_job.rb
app/jobs/podcast_import_job.rb

closes https://github.com/PRX/feeder.prx.org/issues/637

Use the default work queue for podcast import

---

app/assets/stylesheets/app/uploads.scss
app/assets/stylesheets/shared/form.scss
app/helpers/application_helper.rb
app/views/episodes/media/_complete.html.erb
app/views/episodes/media/_error.html.erb
app/views/episodes/media/_new.html.erb
app/views/episodes/media/_processing.html.erb
app/views/images/_new.html.erb

Applies bootstrap `.input-group` styles through the file states (new, processing, error, complete, etc). I think this is a little more polished. Open to suggestions or diverging opinions

Styles Files

---

app/controllers/feeds_controller.rb
app/controllers/podcasts_controller.rb
app/helpers/episodes_helper.rb
app/javascript/controllers/feed_link_controller.js
app/javascript/controllers/unsaved_controller.js
app/models/apple/show.rb
app/models/feed.rb
app/models/feed_token.rb
app/views/episodes/_tabs.html.erb
app/views/feeds/_form.html.erb
app/views/feeds/_form_main.html.erb
app/views/feeds/_tabs.html.erb
app/views/podcast_engagement/_form.html.erb
app/views/podcast_engagement/_form_main.html.erb
app/views/podcast_engagement/_form_status.html.erb
app/views/podcast_engagement/show.html.erb
config/locales/en.yml

Misc bugfixes, from initial feature-parity review.
- Fixes discard button when invalid
- Cleanup Engagement tab
- Fixup some Feed/Episode tab weirdness

Bugfix roundup 1

---

app/controllers/episode_player_controller.rb
app/helpers/embed_player_helper.rb
app/views/episode_player/_form.html.erb
app/views/episode_player/show.html.erb
config/locales/en.yml

Fixes #670. Adds the embed player page on the episode.

Episode embed player

---

app/controllers/episodes_controller.rb
app/controllers/podcasts_controller.rb
app/javascript/controllers/click_controller.js
app/javascript/controllers/tag_select_controller.js
app/policies/episode_policy.rb
test/controllers/episodes_controller_test.rb
test/controllers/podcasts_controller_test.rb
test/policies/episode_policy_test.rb

Some minor cypress test fixes - I forgot to move controller checks to the policies, and some JS stuff.

Cypress fixes

---

app/assets/stylesheets/shared/form.scss
app/javascript/controllers/unsaved_controller.js
app/views/episode_segmenter/_form.html.erb
app/views/episodes/_form_status.html.erb
app/views/feeds/_form_status.html.erb
app/views/podcast_engagement/_form_status.html.erb
app/views/podcasts/_form_main.html.erb
app/views/podcasts/_form_status.html.erb

More styling bug fixes

---

app/models/episode_import.rb
app/views/episodes/_episode.html.erb
app/views/episodes/_form_media.html.erb
app/views/episodes/media/_segment_count.html.erb
app/views/podcasts/show.html.erb

Bugfixes for things I done broke earlier.

Episode medium UI

---

app/assets/stylesheets/shared/form.scss
app/views/episodes/_form_status.html.erb
app/views/feeds/_form_status.html.erb
app/views/podcasts/_form_status.html.erb

Fixes this: https://cav.is/i/Mgjbhl.png
AND this: https://cav.is/i/LdRxsq.png

Fix Rounded Corners

---

app/assets/stylesheets/shared/bootstrap-variables.scss
app/views/episode_segmenter/show.html.erb
app/views/episodes/_form_distribution.html.erb
app/views/episodes/_form_main.html.erb
app/views/episodes/_form_media.html.erb
app/views/episodes/_form_status.html.erb
app/views/episodes/_form_tags.html.erb
app/views/fake/index.html.erb
app/views/fake/show.html.erb
app/views/feeds/_form_ad_zones.html.erb
app/views/feeds/_form_audio_format.html.erb
app/views/feeds/_form_auth.html.erb
app/views/feeds/_form_distribution.html.erb
app/views/feeds/_form_overrides.html.erb
app/views/feeds/_form_status.html.erb
app/views/feeds/_form_tags.html.erb
app/views/images/_complete.html.erb
app/views/images/_error.html.erb
app/views/images/_new.html.erb
app/views/images/_processing.html.erb
app/views/imports/_form_status.html.erb
app/views/layouts/application.html.erb
app/views/podcast_engagement/_form_status.html.erb
app/views/podcast_switcher/_dropdown.html.erb
app/views/podcasts/_form_distribution.html.erb
app/views/podcasts/_form_main.html.erb
app/views/podcasts/_form_status.html.erb
app/views/podcasts/_podcast_page.html.erb
app/views/podcasts/index.html.erb

This fixes base issues. Still some more to get, but we should get them later as these issues persist in Augury

A11y pass #1

---

app/models/episode.rb
app/models/podcast.rb
app/models/publishing_pipeline_state.rb

Sets up more logging around the release of episodes.

More logging for publishing

---

app/controllers/episodes_controller.rb
app/controllers/podcasts_controller.rb
app/models/episode.rb
app/views/episode_media/_form_main.html.erb
app/views/episodes/_form_main.html.erb
app/views/feeds/_form_main.html.erb
app/views/imports/_form_status.html.erb
app/views/podcast_planner/_form_draft_settings.html.erb
app/views/podcasts/_form_main.html.erb

Adds required asterisk indicator to fields.
Also fixed a minor bug of sort-ordering on the podcast#show "Next Scheduled or Draft" card.

Required fields

---

app/jobs/publish_feed_job.rb
app/models/apple/episode.rb
app/models/apple/show.rb
app/models/publishing_pipeline_state.rb
app/models/publishing_queue_item.rb

- adjust some log `error` lines down to `info`
- bump the apple episode asset processing timeout to 10 minutes

Adjust logging

---

app/controllers/imports_controller.rb
app/models/podcast_import.rb
app/views/imports/_form_status.html.erb
config/locales/en.yml

Add option to exclude podcast metadata during import

---

app/assets/stylesheets/shared/trix-custom.scss

Hotfix for height rendering bug on Trix Editor fields

Add form-control css to trix editor

---

app/models/apple/episode.rb

Bump episode asset wait timeout

---

app/models/podcast.rb

Set empty link after save

---

app/models/enclosure_url_builder.rb
test/models/enclosure_url_builder_test.rb

default to .mp3 for any non-wav non-flac media

---

config/environments/production.rb
config/environments/staging.rb
env-example

Closes #839.  Will need to wire this ENV through Infrastructure.  Should test staging first, in case everything goes wrong.

CDN Asset Host

---

app/models/concerns/import_utils.rb
app/models/imports/podcast_rss_import.rb
lib/feedjira/parser/podcast.rb
test/models/imports/podcast_rss_import_test.rb

RSS import parity

---

app/jobs/application_job.rb
app/jobs/publish_feed_job.rb
app/jobs/unlink_job.rb
app/models/feed.rb
app/views/feeds/_form_distribution.html.erb
test/jobs/publish_feed_job_test.rb
test/models/feed_test.rb

Fixes #840.
Fixes #852.
Fixes #883.
Fixes all the things.

Feed fixups

---

app/controllers/episodes_controller.rb
app/helpers/episodes_helper.rb
app/models/episode.rb
app/views/episodes/_form_main.html.erb
config/locales/en.yml

Fixes #907.
Adds a new getter/setter virtual field to the Episode model.

Display nil explicit as "inherit"

---

app/models/media_resource.rb
app/models/tasks/copy_media_task.rb
app/models/tasks/fix_media_task.rb

Realizing I forgot cache (and other) headers on the more recent porter tasks.

Add some missing cache headers on media

---

app/views/layouts/application.html.erb
app/views/layouts/plain.html.erb

HOTFIX: Rename page title fallback to Dovetail Podcasts

---

config/locales/en.yml

Change Podcast "profile image" to "cover image"

---

docker-compose-ci.yml
docker-compose.yml

Postgres 16.2

---

app/models/imports/podcast_rss_import.rb
test/models/imports/podcast_rss_import_test.rb

Handle nil and blank itunes owner

---

Gemfile
Gemfile.lock
lib/slack_helper.rb

Not tested. Needs policy update in Infra

Replace SNS with EventBridge for Slack messages

---

app/models/apple/publisher.rb
test/models/apple/publisher_test.rb

Update episodes still drafting in Apple

---

config/locales/en.yml

1 line change. Requested by Distro. (Users were confused by the term "fresh form")
Thanks 👍

HOTFIX: Revised stale_record_modal verbiage

---

app/helpers/feeds_helper.rb
app/policies/apple/config_policy.rb
app/views/feeds/_form.html.erb
app/views/feeds/_form_apple_config.html.erb
config/locales/en.yml

Adds the Apple Config UI to an existing `Feeds::AppleSubscription` only, in preparation for another PR to add "Add Apple Subscription Feed" UI

Feat/apple feed UI

---

app/models/episode.rb
test/models/episode_test.rb

Strip guids of leading and trailing whitespace

---

app/models/podcast_planner.rb
app/views/podcast_planner/_form_calculator_dates.html.erb
app/views/podcast_planner/_form_draft.html.erb

Allow longer production plans

---

app/models/episode.rb
app/models/transcript.rb
db/migrate/20240626182801_create_transcripts.rb
db/schema.rb

Add table migration and init model

---

app/javascript/controllers/import_timings_controller.js

small change in order to solve some async issues in acceptance testing for the timings import.

Move async line to beginning of upload method

---

app/assets/stylesheets/shared/layout.scss
app/assets/stylesheets/shared/tabs.scss
app/views/episode_media/_form.html.erb

See: https://prx.slack.com/archives/CG7G1FPNJ/p1720705946618059

fix z-index issues

---

app/views/feeds/_form_apple_config.html.erb

Requested by Stacy.
https://help.prx.org/hc/en-us/articles/26602803552155-Setting-up-Apple-Podcast-Subscriptions-with-Apple-Delegated-Delivery

HOTFIX: updated link to help doc for apple subscriptions

---

app/javascript/controllers/tag_select_controller.js

Remove last item added if dupe

---

app/models/imports/podcast_rss_import.rb

More large-RSS import fixes

---

app/helpers/feeds_helper.rb
app/models/concerns/feed_audio_format.rb
app/models/feed.rb
app/models/validators/audio_format_validator.rb
config/locales/en.yml

We should be setting a bitrate not a bitdepth for aac / m4a files. oops

AAC bit rate (not bit depth)

---

app/assets/stylesheets/shared/header-nav.scss
app/views/layouts/_nav.html.erb
config/locales/en.yml

This makes a few small adjustments to the styling of nav icons and menus, as seen in the comparison video below.
There was no one asking for these changes, so this PR can be closed if no one wants them.
The CSS was brute forced pretty hard, so I imagine there should be some refactoring to make some of these changes the right way.
https://github.com/user-attachments/assets/8c0bf8ad-3d22-42af-aa3a-65a83dafd0b3

Adjust nav icon and menu styles

---

app/javascript/controllers/apple_key_controller.js
app/models/apple/key.rb
app/models/feeds/apple_subscription.rb
test/models/apple/key_test.rb
test/models/feed/apple_subscription_test.rb

removes the unnecessary parsing of the apple key. also fixes token instantiation for apple feeds.

Remove buggy parsing method

---

app/controllers/episodes_controller.rb
app/controllers/feeds_controller.rb
app/controllers/podcasts_controller.rb
app/helpers/podcasts_helper.rb
app/models/concerns/import_utils.rb
app/models/concerns/text_sanitizer.rb
app/models/episode.rb
app/models/feed.rb
app/models/imports/episode_rss_import.rb
app/models/imports/podcast_rss_import.rb
app/models/podcast.rb
app/representers/api/auth/feed_representer.rb
app/representers/api/episode_representer.rb
app/representers/api/podcast_representer.rb
app/views/episodes/_form_main.html.erb
app/views/feeds/_form_overrides.html.erb
app/views/podcasts/_form_main.html.erb
app/views/podcasts/show.rss.builder
test/factories/episode_factory.rb
test/factories/feed_factory.rb
test/models/concerns/text_sanitizer_test.rb
test/models/imports/podcast_rss_import_test.rb
test/representers/api/auth/feed_representer_test.rb
test/representers/api/episode_representer_test.rb

fixes #1030 using option 3 from that ticket

Deprecate summary and content attributes, and fix description, summary, content text formats in the RSS feeds

---

.tool-versions
Dockerfile
Gemfile
Gemfile.lock

Bump Ruby from 3.3.5 to 3.3.6

---

app/models/feed.rb
app/models/validators/redirect_prefix_validator.rb
config/locales/en.yml
test/models/validators/redirect_prefix_validator_test.rb

Validate enclosure prefixes

---

app/helpers/embed_player_helper.rb
test/helpers/embed_player_helper_test.rb

Don't include prefixes in enclosure preview urls

---

app/models/concerns/image_file.rb
app/models/episode.rb
app/models/feed.rb
test/controllers/api/episodes_controller_test.rb

Update episode image attributes without replacing

---

config/locales/en.yml

Closes #1195 
En.yml file change with [Paloma approved verbiage](https://prx.slack.com/archives/C07L9VB7XSM/p1743022560803709?thread_ts=1742925355.910399&cid=C07L9VB7XSM)

fix episode_url help text

---

app/models/podcast.rb
test/factories/podcast_factory.rb
test/models/podcast_test.rb

Only set guid after save, only set if blank

---

app/models/megaphone/config.rb
app/models/megaphone/podcast.rb

fixes a couple bugs found testing in staging

Fix blank tags, allow span opt in attribute

---

app/models/concerns/import_utils.rb
app/models/imports/episode_rss_import.rb
app/models/imports/podcast_rss_import.rb
config/locales/en.yml
lib/feedjira/parser/podcast.rb
test/fixtures/transistor_locked.xml
test/models/concerns/import_utils_test.rb
test/models/imports/podcast_rss_import_test.rb

Import fixes

---

app/assets/stylesheets/shared/card.scss
app/assets/stylesheets/shared/form.scss

closes #1267 
-syncs global styles with https://github.com/PRX/augury.prx.org/pull/1834
-fixes checkboxes/toggles in darkmode

HOTFIX: Sync global styles (dark mode checkboxes)

---

app/controllers/podcast_metrics_controller.rb
app/helpers/podcasts_helper.rb
app/views/layouts/_subnav.html.erb
app/views/podcast_metrics/show.html.erb
config/routes.rb

This PR adds the metrics tab (development only) and a skeleton layout for the tab.

Adds a metrics tab and skeleton layout

---

app/controllers/feeds_controller.rb
app/views/feeds/_form_distribution.html.erb
app/views/podcasts/show.rss.builder
config/locales/en.yml
db/migrate/20250706201302_add_import_locked_to_feeds.rb
db/schema.rb

Add import locked for `podcast:import` tag

---

app/models/imports/episode_megaphone_import.rb
app/models/imports/podcast_megaphone_import.rb

Megaphone import fixes 1

---

app/models/subscribe_link.rb

1291: Remove `apollo` from subscription links

---

app/models/concerns/publishing_notify.rb
test/models/concerns/publishing_notify_test.rb

Do not send podping for blank urls

---

app/models/imports/podcast_megaphone_import.rb
test/models/imports/podcast_megaphone_import_test.rb

Default podcast values for megaphone import

---

app/models/megaphone/podcast.rb
test/models/megaphone/podcast_test.rb

wasn't using the image model href

Set podcast image correctly

---

app/models/concerns/episode_media.rb
app/models/media_version.rb

The show endpoints are lagging!

Faster latest-media-version for episodes#show
